var catalog=UnityEditor.AssetDatabase.LoadAssetAtPath<Jcc.Presentation.ReplayAssetCatalog>("Assets/Res/Replay/ReplayAssets.asset");
var list=new System.Collections.Generic.List<Jcc.Presentation.ReplayAssetCatalog.Entry>(catalog.entries);
if(!list.Exists(x=>x.key=="item/mittens")){var sprite=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Sprite>("Assets/Res/GUI/Image/Equipment/mittens.png");if(!sprite)throw new System.Exception("Missing item/mittens");list.Add(new Jcc.Presentation.ReplayAssetCatalog.Entry{key="item/mittens",sprite=sprite});}
if(!list.Exists(x=>x.key=="item/lightshield_crest")){var sprite=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Sprite>("Assets/Res/GUI/Image/Equipment/lightshield_crest.png");if(!sprite)throw new System.Exception("Missing item/lightshield_crest");list.Add(new Jcc.Presentation.ReplayAssetCatalog.Entry{key="item/lightshield_crest",sprite=sprite});}
if(!list.Exists(x=>x.key=="item/talisman_of_ascension")){var sprite=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Sprite>("Assets/Res/GUI/Image/Equipment/talisman_of_ascension.png");if(!sprite)throw new System.Exception("Missing item/talisman_of_ascension");list.Add(new Jcc.Presentation.ReplayAssetCatalog.Entry{key="item/talisman_of_ascension",sprite=sprite});}
if(!list.Exists(x=>x.key=="item/5004")){var sprite=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Sprite>("Assets/Res/GUI/Image/Equipment/5004.png");if(!sprite)throw new System.Exception("Missing item/5004");list.Add(new Jcc.Presentation.ReplayAssetCatalog.Entry{key="item/5004",sprite=sprite});}
if(!list.Exists(x=>x.key=="item/forbidden_idol")){var sprite=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Sprite>("Assets/Res/GUI/Image/Equipment/forbidden_idol.png");if(!sprite)throw new System.Exception("Missing item/forbidden_idol");list.Add(new Jcc.Presentation.ReplayAssetCatalog.Entry{key="item/forbidden_idol",sprite=sprite});}
if(!list.Exists(x=>x.key=="augment/thegoldendragon2")){var sprite=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Sprite>("Assets/Res/GUI/Image/Augment/thegoldendragon2.png");if(!sprite)throw new System.Exception("Missing augment/thegoldendragon2");list.Add(new Jcc.Presentation.ReplayAssetCatalog.Entry{key="augment/thegoldendragon2",sprite=sprite});}
if(!list.Exists(x=>x.key=="cover/frontline-two-v1")){var sprite=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Sprite>("Assets/Res/GUI/Image/Cover/frontline-two-v1.png");if(!sprite)throw new System.Exception("Missing cover/frontline-two-v1");list.Add(new Jcc.Presentation.ReplayAssetCatalog.Entry{key="cover/frontline-two-v1",sprite=sprite});}
catalog.entries=list.ToArray();UnityEditor.EditorUtility.SetDirty(catalog);UnityEditor.AssetDatabase.SaveAssets();return "Episode 2 assets registered";