// Generated by prepare_engine.py from combat/*; edit the modules, not this file.

// ---- combat/prelude.hpp ----
// Conditional 30 Hz single-frontline equipment benchmark. Not a game-client emulator.
// Inputs and approximation contracts are documented in report.md and mechanics.md.
#include <algorithm>
#include <stdexcept>
#include <array>
#include <atomic>
#include <cassert>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <mutex>
#include <numeric>
#include <sstream>
#include <string>
#include <thread>
#include <vector>
#include "generated.hpp"
using namespace std;
constexpr double EPS=1e-8;
struct Options {
 int fps=30,seconds=180,frequency=3,lock=30,pause=9,edgeFrames=15,stage=4;
 double physicalShare=.5,wound=0;int woundStart=0,woundEnd=5400,resistanceMode=0;
 double dps=1400,targetRes=50,targetHP=3000,axe=.04,dawn=.15,post=.03,aoeVamp=1;
 int attackers=1;bool soloPlate=false;
 int allyPeriod=120,allyDeath=1000000;
 bool malphiteManaDuringShield=false,malphiteAttacksDuringShield=false,malphiteBurstOnExpiry=true;
 bool skills=true,shieldMana=true,control=false,itemVamp=false,gunSelf=false,trace=false;
};

// ---- combat/equipment.hpp ----
struct Build {
 vector<int> ids;int cat=0;unsigned char c[NK][2]{};
 double hp=0,a=0,m=0,ap=0,ad=0,as=0,crit=0,regen=0,sv=0,dr=1,da=0,critmult=0,hpp=0;
 int n(int k) const{return c[k][0]+c[k][1];}
 double w(int k,double normal,double rad)const{return c[k][0]*normal+c[k][1]*rad;}
};
Build makeBuild(vector<int> ids,int glove=0){
 Build b;b.ids=ids;int na=0,nr=0,np=0;
 for(int i:ids)if(i>=0){auto e=ITEMS[i];if(e.kind>=0)b.c[e.kind][e.rad]++;b.hpp+=e.hpp;b.hp+=e.hp;b.a+=e.a;b.m+=e.m;b.ap+=e.ap;b.ad+=e.ad;b.as+=e.as;b.crit+=e.crit;b.regen+=e.regen;b.sv+=e.sv;b.dr*=1-e.dr;b.da+=e.da;b.critmult+=e.critmult;na+=e.cat==2;nr+=e.cat==1;np+=e.cat==3;}
 b.cat=np?5:na>1||nr>1?4:na&&nr?3:na?2:nr?1:0;
 if(glove){b.hp+=150;b.crit+=.2;b.cat=glove==1?6:7;}
 b.hpp+=b.w(WARMOG,.18,.36)+b.w(BRAMBLE,.06,.12)+b.w(DCLAW,.06,.28)+b.w(SUNFIRE,.08,.16)+b.n(UNBREAKABLE)*.15;
 return b;
}
bool legal(vector<int> ids){for(int id:ids)if(id>=0&&ITEMS[id].cat==3)return false;for(size_t j=1;j<ids.size();j++)if(ids[j]>=0&&ids[j]==ids[j-1]&&(ITEMS[ids[j]].unique||ITEMS[ids[j]].cat==2))return false;return true;}

struct EquipmentState {
 int manazaneRemaining=0,manaPotRemaining=0,manazaneStart=0,potStart=0,brambleReady=0;
 bool vow=false,sterak=false,blood=false,edge=false,zhonya=false,healthPot=false,covenantDied=false;
 array<double,121> debtChanges{};double debtRate=0;
};

// ---- combat/attributes.hpp ----
struct Result {
 int frame=0,casts=0,attacks=0,spiderAttacks=0;bool alive=true;
 double hp=0,H=0,initialHP=0,shield=0,heal=0,overheal=0,vamp=0,skillHeal=0,spiderHeal=0,damage=0,granted=0,used=0,lost=0,converted=0,growth=0,raw=0,avoided=0,ccAvoided=0,deferred=0,debtPaid=0,debtForgiven=0,debtLeft=0,mana=0,mpInitial=0,mpGain=0,mpSpent=0,mpBlocked=0,mpOverflow=0,mpAttack=0,mpDamage=0,mpRegen=0,mpSpecial=0,minHP=1e30;
};

// Hero is the immutable, star-specific base-attribute/skill catalog record.
using BaseAttributes = Hero;
struct CombatAttributes {
 double hp,H,A,M,healthFactor,mp,cap,attackCharge=0,extraA=0,extraM=0,bonusAP=0,bonusAD=0;
 double lastAmp=1,lastAD=1,crit=0,critFactor=1,spellCrit=1,sv=0,ampDamage=1;
};

// ---- combat/states.hpp ----
// Behaviour restrictions are independent of Buff storage. Effects own leases,
// and may only release their own lease; overlapping restrictions remain active.
enum class CombatAction : unsigned {Mana=0,DirectMana=1,Cast=2,Attack=3,Untargetable=4};
using StateHandle=unsigned;
using StateMask=unsigned;
constexpr StateMask stateBit(CombatAction a){return 1u<<static_cast<unsigned>(a);}
constexpr StateMask ShieldManaLock=stateBit(CombatAction::Mana)|stateBit(CombatAction::DirectMana)|stateBit(CombatAction::Cast);
struct CombatStates {
 struct Lease {StateHandle handle=0;StateMask mask=0;};
 array<Lease,32> leases{};int count=0;StateHandle next=1;
 array<int,5> references{};
 int castLockEnd=0,attackPauseEnd=0,stasisEnd=0;
 // Some channels also prohibit direct equipment mana grants.
 int directManaLockEnd=0;
 StateHandle acquire(StateMask mask){if(!mask)return 0;assert(count<int(leases.size()));StateHandle id=next++;assert(id!=0);leases[count++]={id,mask};for(unsigned i=0;i<5;i++)if(mask&(1u<<i))references[i]++;return id;}
 void release(StateHandle id){if(!id)return;for(int n=0;n<count;n++)if(leases[n].handle==id){for(unsigned i=0;i<5;i++)if(leases[n].mask&(1u<<i)){assert(references[i]>0);--references[i];}leases[n]=leases[--count];return;}}
 bool held(CombatAction a)const{return references[static_cast<unsigned>(a)]>0;}
 bool blocked(CombatAction a,int frame)const{
  if(held(a))return true;
  switch(a){
   case CombatAction::Mana:return frame<castLockEnd;
   case CombatAction::DirectMana:return frame<directManaLockEnd;
   case CombatAction::Cast:return frame<castLockEnd||frame<stasisEnd;
   case CombatAction::Untargetable:return false;
   case CombatAction::Attack:return frame<attackPauseEnd||frame<stasisEnd;
  }return false;
 }
};

// ---- combat/buffs.hpp ----
// Fixed-capacity storage: no per-tick allocation or virtual dispatch.
enum class BuffSource {Skill,PassiveSkill,Equipment,Trait};
enum class BuffId {SpiderHaste,ViHaste,ReksaiHealing,HecarimResistance,DamageReduction,EdgeInvulnerability,Stasis,Flail,Titan,Mogul,ShenStrikes,TaricStrikes,LichStrikes,Ascension,XayahFeathers,WarwickHaste,Rapidfire,Spellweaver,CarryHaste,CarryAD,CarryEmpower,CarrySummons,CarrySlow,CarryCurse,CarryAmplify,Count};
enum class BuffRefresh {Replace,Extend};
struct Buff {BuffSource source=BuffSource::Skill;int end=0,stacks=0;double magnitude=0;bool active(int frame)const{return frame<end;}};
enum class ShieldEndReason {Broken,Expired,Replaced,Removed};
struct Shield {double value=0,decay=0;int end=0,tag=0;BuffSource source=BuffSource::Equipment;StateHandle stateHandle=0;double armor=0,magicResist=0;};
struct Hot {double heal=0,physical=0,magic=0;int end=0;bool aoe=false;int start=0;};
enum class HealthBand {Below,Half,Above};
struct DravenWound {double perTick;int remaining;};
struct BuffState {
 vector<DravenWound> dravenWounds;
 HealthBand justiceBand=HealthBand::Above;
 array<Buff,static_cast<size_t>(BuffId::Count)> effects{};
 array<Shield,16> shields{};int ns=0;
 array<Hot,8> hots{};int nh=0;
 bool petrified=false;StateHandle petrificationState=0;
 Buff& get(BuffId id){return effects[static_cast<size_t>(id)];}
 const Buff& get(BuffId id)const{return effects[static_cast<size_t>(id)];}
 // Refresh policy is explicit; duration ending is exclusive (frame < end).
 void apply(BuffId id,int end,BuffSource source=BuffSource::Skill,double magnitude=0,BuffRefresh policy=BuffRefresh::Replace){auto& b=get(id);b.source=source;b.end=policy==BuffRefresh::Extend?max(b.end,end):end;b.magnitude=magnitude;}
 void setStacks(BuffId id,int count,BuffSource source=BuffSource::Skill){auto& b=get(id);b.source=source;b.stacks=count;}
 void addStack(BuffId id,int cap,BuffSource source=BuffSource::Equipment){auto& b=get(id);b.source=source;b.stacks=min(cap,b.stacks+1);}
 void consume(BuffId id){auto& b=get(id);if(b.stacks>0)--b.stacks;}
 double shieldResistance(bool armor)const{double value=0;for(int i=0;i<ns;i++)if(shields[i].value>EPS)value+=armor?shields[i].armor:shields[i].magicResist;return value;}
};
struct SkillState {bool transformed=false,half=false,taric=false,sett=false,kobukoSmash=false;double treeBlocked=0;};

// ---- combat/outgoing.hpp ----
// Opt-in output benchmark. Default construction leaves historical tank simulation unchanged.
struct OutputTarget {
 double maxHealth=3000,armor=50,magicResist=50,shield=0,damageReduction=0,vulnerability=0;
 bool finite=false,isTank=false;
};
struct OutputConfig {
 bool enabled=false,retainEvents=false;
 // Expanded skills require a declared scenario, never silent guessed timing.
 bool expandedScenario=false,targetIsolated=true,fullMoon=false,ivernTargetsSelf=false,gnarLastEnemy=false;
 bool moonCycle=false;int moonStartPhase=0; // explicit assumed five-phase cycle, 0=new, 4=full
 int fullMoonEnemyCount=1; // number of enemies sharing full-moon damage
 int plantAttackIntervalFrames=0,lunaraHitCount=0; // caller must supply unresolved geometry/cadence
 int invokerUnits=0,executionerUnits=0,summonerUnits=0,adaptorUnits=0;
 bool blueCanRegen=true; // declared channel policy, measured timing not claimed
 bool empoweredManaLock=true;

 int spiritBlossomUnits=0,lunarUnits=0; // Explicit native-race conditions; implemented baselines 3 and 2.
 bool primalBear=false; // 2 Primal, Bear blessing: own damage executes strictly below 12% HP.
 int infernoUnits=0; // Explicit race condition; 0/2/3/5/7, independent of ordinary burn.
 int rapidfireUnits=0,slayerUnits=0,spellweaverUnits=0;
 vector<int> alliedSpellweaverCastFrames; // explicit external cast events, empty = self only
 int hunterUnits=0; // explicit fixed-target benchmark trait; no emblem implied
 int elderFlightFrames=-1; // unknown in source; caller must explicitly supply measured/assumed duration
 int dravenAxeHits=1,dravenReturnFrames=15;
 double attackMana=-1,baseManaRegen=0;bool xayahEmpowerManaLock=false;
 OutputTarget target;
 int targetCount=1;double distance=1; // first milestone: one stationary adjacent target
 double armorPenetration=0,magicPenetration=0,flatArmorPenetration=0,flatMagicPenetration=0;
};
enum class DamageSource {Attack,Skill,Equipment};
struct OutgoingEvent {
 int frame;DamageSource source;string detail;
 double physical,magic,trueDamage,criticalMultiplier,preMitigation,mitigated,absorbed,healthDamage,overkill;
};
struct DamageLedger {
 OutputConfig config;double hp=0,shield=0,total=0,potential=0;
 array<double,3> bySource{},byType{};
 vector<OutgoingEvent> events;vector<array<double,5>> curve;
 explicit DamageLedger(const OutputConfig& c={}):config(c),hp(c.target.maxHealth),shield(c.target.shield){}
 bool alive()const{return !config.target.finite||hp>EPS;}
 static double resistance(double value){return value>=0?100/(100+value):2-100/(100-value);}
 double apply(int frame,DamageSource source,const char* detail,double physical,double magic,double pure,double crit,double amp,double armor,double mr){
  if(!alive())return 0;
  double ar=armor>=0?max(0.,armor*(1-config.armorPenetration)-config.flatArmorPenetration):armor;
  double me=mr>=0?max(0.,mr*(1-config.magicPenetration)-config.flatMagicPenetration):mr;
  double scale=amp*(1+config.target.vulnerability);
  double p=physical*crit*scale*resistance(ar)*(1-config.target.damageReduction);
  double m=magic*crit*scale*resistance(me)*(1-config.target.damageReduction);
  double t=pure*amp; // explicit policy: true damage bypasses target mitigation and cannot crit
  double value=p+m+t,absorbed=min(shield,value);shield-=absorbed;
  double health=config.target.finite?min(hp,value-absorbed):value-absorbed;
  if(config.target.finite)hp-=health;
  double effective=absorbed+health;potential+=value;total+=effective;bySource[int(source)]+=effective;
  if(value>0){byType[0]+=effective*p/value;byType[1]+=effective*m/value;byType[2]+=effective*t/value;}
  if(config.retainEvents)events.push_back({frame,source,detail,physical,magic,pure,crit,(physical+magic)*crit*amp+pure*amp,value,absorbed,health,value-effective});
  return effective;
 }
 void sample(int frame,int fps){if(config.enabled&&frame%fps==0)curve.push_back({double(frame)/fps,total,bySource[0],bySource[1],bySource[2]});}
};

// ---- combat/carry.hpp ----
enum CarryKind {CarryXayah=100,CarryCaitlyn,CarryKayle,CarryWarwick,CarryVeigar,CarryKarma,CarryAphelios,CarryAhri,CarryDraven,CarryElderDragon,CarryCamille,CarryAkali,CarryVarus,CarryBramble,CarryBlueSentry,CarryShadowWolf,CarryYunara,CarryLeblanc,CarryGromp,CarryTeemo,CarryRengar,CarryKhazix,CarryYi,CarryTristana,CarryRaptor,CarryAzir,CarryCassiopeia,CarryKogmaw,CarryMorgana,CarryRedBuff,CarryNidalee,CarryEzreal,CarrySivir,CarryZyra,CarrySoraka,CarryKennen,CarryAshe,CarryLunara,CarryLux,CarryDiana,CarryGnar,CarryIvern,CarryAkaliAP,CarryYiAP,CarryKogmawAP,CarryGrompAD,CarryNidaleeAD,CarryEnd};
struct CarryHit {int frame;double physical,magic;bool needsTarget=true;};
struct CarryPeriodic {int next,end,interval;double physical,magic,healthRatio=0;};
struct CarryState {
 vector<CarryPeriodic> periodic;
 int moonCasts=0;
 StateHandle empowerLease=0;int bombAttacks=0,bombEnd=0,blueEnd=0;double bombAD=0;bool marked=false,gnarTransformed=false;
vector<CarryHit> pending;StateHandle channelLease=0,xayahLease=0;int channelEnd=0;
 StateHandle elderFlightLease=0;int elderLandFrame=0;bool elderTransformed=false;};

// ---- combat/battle-contracts.hpp ----
struct HeroEntity;
struct BattleSystem;
struct DamageRequest {
 int source,target,frame;unsigned long long sequence;
 double physical,magic,crit,amp,vamp;bool spell,item,aoe;
 bool needsTarget=true;
 double pure=0,flatArmor=0,flatMR=0,innateMRShred=0,armorPenetration=0;
};
void submitDamage(HeroEntity&,double,double,bool,bool,bool,bool needsTarget=true);

void submitCast(HeroEntity&,double);

void submitElderEffect(HeroEntity&,bool landing);

// Cross-entity skill effects are queued and settled by BattleSystem.
enum class CarryEffectKind {Slow,Stun,Burn,Remove};
void submitCarryEffect(HeroEntity&,CarryEffectKind,double,int);
bool targetBurning(HeroEntity&);

// ---- combat/simulation.inc ----
struct HeroEntity {
 BattleSystem* battle=nullptr;int entityId=-1;bool cannotDie=false;
 private:
 friend struct BattleSystem;
 bool systemTick=false;
 public:
 const BaseAttributes& h;const Scenario& sc;const Build& b;Options o;Result r;int aug,f=0,F,limit,hitInterval;
 CombatAttributes unit;
 BuffState buffs;
 CombatStates states;
 EquipmentState equipment;
 SkillState skill;CarryState carry;
 DamageLedger output;long long windupEnd=-1;StateHandle windupLease=0;
 bool liveTargetAvailable=true;StateHandle liveStunLease=0;int liveStunEnd=0;
 double fixedArmorShred=0,fixedMRShred=0;
 double liveArmorShred=0,liveMRShred=0;int liveArmorShredEnd=0,liveMRShredEnd=0,liveWoundEnd=0;
 int outputBurnNext=0,outputArmorShredEnd=0,outputMagicShredEnd=0;string outputBurnSource="burn";
 int enemyStun[3]{};
 double burnEnd[3]{},burnRatio[3]{},enemyA[3],enemyM[3],flatA[3]{},flatM[3]{},lastJewel[3]{},shredA[3]{},shredM[3]{};








 bool capture=true;
 struct WebEvent {int frame;string kind;double value;};
 vector<array<double,19>> frames;
 vector<WebEvent> events;
 struct PresentationEvent {int frame;string kind;double amount;string source;};
 vector<array<double,4>> attributes;
 vector<PresentationEvent> presentationEvents;
 void presentationEvent(const char* kind,double amount,const char* source){if(capture)presentationEvents.push_back({f,kind,amount,source});}
 void snapshot(){if(!capture)return;frames.push_back({double(f),max(0.,unit.hp),unit.H,totalShield(),unit.mp,unit.cap,double(max(0,states.castLockEnd-f)),double(max(0,states.attackPauseEnd-f)),double(r.casts),double(r.attacks),r.heal,r.used,r.damage,defenses(true),defenses(false),double(skill.transformed),double(f<buffs.get(BuffId::Stasis).end||f<buffs.get(BuffId::EdgeInvulnerability).end),double(r.alive),r.mpBlocked});attributes.push_back({double(f),defenses(true),defenses(false),100*abilityPowerMultiplier()});}
 ostream* trace=nullptr;
 HeroEntity(const Hero& hh,const Scenario& ss,const Build& bb,int aa,const Options& oo,ostream* tt=nullptr,const OutputConfig& out={}):h(hh),sc(ss),b(bb),o(oo),aug(aa),F(o.fps),limit(o.seconds*o.fps),hitInterval(o.fps/o.frequency),trace(tt),output(out){
  r.frame=limit;
  double brawl=sc.brawl==2?.25:sc.brawl==4?.4:sc.brawl==6?.65:0;
  unit.healthFactor=1+(out.spiritBlossomUnits==3?.10:0)+b.hpp+brawl+(o.soloPlate&&b.c[GARGOYLE][0]?.17:0);unit.H=(h.hp+b.hp+((aug&2)?600:0)+400*b.n(HULL))*unit.healthFactor;unit.hp=unit.H;
  double guard=sc.guard==2?25:sc.guard==4?60:sc.guard==6?120:0;
  unit.A=h.a+b.a+guard+b.w(GARGOYLE,10,20)*o.attackers+(h.role<2?b.w(HELM,30,80):0);
  unit.M=h.m+b.m+guard+b.w(GARGOYLE,10,20)*o.attackers+(h.role<2?b.w(HELM,30,80):0);
  unit.mp=h.mp;unit.cap=max(15.,h.cap-10*b.n(DAWNCORE));r.initialHP=unit.H;r.mpInitial=unit.mp;
  for(int i=0;i<3;i++){enemyA[i]=enemyM[i]=o.targetRes;lastJewel[i]=-1000;if(output.config.enabled){enemyA[i]=out.target.armor;enemyM[i]=out.target.magicResist;}}
 }
 void event(const string& k,double v=0){if(capture)events.push_back({f,k,v});if(trace)*trace<<f<<','<<fixed<<setprecision(6)<<double(f)/F<<','<<k<<','<<v<<','<<unit.hp<<','<<unit.H<<','<<unit.mp<<','<<totalShield()<<'\n';}
 double heal(double v,int src=0);
 void grow(double v){unit.H+=v;unit.hp+=v;refreshHealthBuffs();r.growth+=v;if(v!=0)presentationEvent("healthGrowth",v,"maxHealth");}


 // Active skill shield contract: own skill shield locks every mana source; item/trait shields do not.




 void gain(double v,int src,bool bypass=false);


 double res(double x){return x>=0?100/(100+x):2-100/(100-x);}
 // Target dummies do not die: no kill-trigger stats or reduction of the prescribed input DPS.
 // Damage quantities are mitigated against target resistances, not a fabricated constant heal budget.
 double deal(double physical,double magic,int target=0,bool spell=false,bool item=false,bool aoe=false,bool needsTarget=true){
  if(physical+magic<=0)return 0;
  if(battle){if(target==0)submitDamage(*this,physical,magic,spell,item,aoe,needsTarget);return 0;}
  if(output.config.enabled&&(target!=0||!output.alive()))return 0;
  if(output.config.enabled){if(f>=outputArmorShredEnd)shredA[0]=0;if(f>=outputMagicShredEnd)shredM[0]=0;if(!item&&b.n(LASTWHISPER))outputArmorShredEnd=f+3*F;if(!item&&b.n(VOIDSTAFF))outputMagicShredEnd=f+5*F;}
  if(b.n(LASTWHISPER)&&!item)shredA[target]=max(shredA[target],.3);
  if(b.n(VOIDSTAFF)&&!item)shredM[target]=max(shredM[target],.3);
  double am=(b.n(EVENSHROUD)?max(.3,shredA[target]):shredA[target]);double mm=(b.n(IONIC)?max(.3,shredM[target]):shredM[target]);
  double ar=max(0.,enemyA[target]-flatA[target])*(1-am),mr=max(0.,enemyM[target]-flatM[target])*(1-mm);
  double phys=physical*res(ar),mag=magic*res(mr);double critScale=spell?unit.spellCrit:1;
  double damageScale=item?1:unit.ampDamage;double d=(phys+mag)*damageScale*critScale;
  if(output.config.enabled){
   double outAr=(enemyA[target]-flatA[target])*(1-am),outMr=(enemyM[target]-flatM[target])*(1-mm);
   auto source=item?DamageSource::Equipment:spell?DamageSource::Skill:DamageSource::Attack;
   d=output.apply(f,source,item?"equipment":spell?"skill":"attack",physical,magic,0,spell?unit.spellCrit:item?1:unit.critFactor,damageScale,outAr,outMr);
  }
  r.damage+=d;
  double vampEligible=(!item||o.itemVamp)?d:0;
  heal(vampEligible*(unit.sv+(o.gunSelf?b.w(GUNBLADE,.2,.4):0))*(aoe?o.aoeVamp:1),1);
  if(mag>0&&b.n(WITS))heal(mag*damageScale*critScale*.25*b.n(WITS),1);
  if(!item&&(b.n(RED)||b.n(MORELLO)))applyBurn(target,(b.n(MORELLO)?10:5)*F,b.c[RED][1]||b.c[MORELLO][1]?.02:.01,b.n(MORELLO)?"morello":"red_buff");
  if(mag>0&&b.n(BLIGHT)&&f-lastJewel[target]>=.5*F){if(mr<=EPS)gain(4*b.n(BLIGHT),3);else flatM[target]+=3*b.n(BLIGHT);lastJewel[target]=f;}
  return d;
 }
 void applyBurn(int target,int duration,double ratio,const char* source){
  if(output.config.enabled&&target==0){if(burnEnd[0]<f||!outputBurnNext)outputBurnNext=f+F;if(ratio>=burnRatio[0])outputBurnSource=source;}
  burnEnd[target]=max(burnEnd[target],double(f+duration));burnRatio[target]=max(burnRatio[target],ratio);
 }
 void aoe(double p,double m,bool spell=true,bool item=false){for(int j=0;j<3;j++)deal(p,m,j,spell,item,true);}
 void stun(double secs,int n=3){if(o.control)for(int j=0;j<n;j++)enemyStun[j]=max(enemyStun[j],f+int(round(secs*F)));}

 double currentAttackSpeed(){
     double asBonus=lunarBonus()+rapidfireAS()+carryAttackSpeedBonus()+b.as+(h.role==1?.2:0)+b.w(RAGE,.07,.16)*(f/F)+b.w(QSS,.03,.06)*(f/F)+b.n(FLICKER)*.04*r.attacks+b.n(GAMBLER)*.3;
     if(b.n(AXE))asBonus+=b.n(AXE)*1.5*(1-unit.hp/unit.H);
     if(r.attacks>=15)asBonus+=b.w(KRAKEN,.15,.30);
     if(f<buffs.get(BuffId::SpiderHaste).end)asBonus+=buffs.get(BuffId::SpiderHaste).magnitude*double(buffs.get(BuffId::SpiderHaste).end-f)/(4*F);
     if(f<buffs.get(BuffId::ViHaste).end)asBonus+=buffs.get(BuffId::ViHaste).magnitude;
     if(buffs.get(BuffId::ShenStrikes).stacks)asBonus+=.4;
     return b.n(SILVERMERE)?.5:max(0.,min(5.,h.as*(1+asBonus)*(buffs.get(BuffId::CarrySlow).active(f)?1-buffs.get(BuffId::CarrySlow).magnitude:1)));
 }
 void attack(){
  r.attacks++;if(output.config.enabled&&output.config.rapidfireUnits==3)buffs.addStack(BuffId::Rapidfire,10,BuffSource::Trait);buffs.addStack(BuffId::Titan,25);stats();
  double p=h.ad*unit.lastAD*(output.config.enabled?1:unit.critFactor),m=0;
  skillAttackDamage(p,m);carryModifyAttack(p,m);
  deal(p,m,0,false);
  skillOnAttack();carryAfterAttack();
  equipmentOnAttack();
  double mana=h.role==0?5:h.role==1?10:(h.star==3?20:5);
  if(output.config.enabled&&output.config.attackMana>=0)mana=output.config.attackMana;
  gain(mana+b.w(SHOJIN,5,10)+b.w(NASHOR,2,4)+2*unit.crit*b.n(NASHOR),0);carryAfterAttackMana();event("attack",r.attacks);
 }

 void trigger(){
  if(unit.hp<=0)return;
  if(!skill.half&&sc.z&&unit.hp<=.5*unit.H){skill.half=true;shield((sc.z==2?.18:sc.z==4?.3:.4)*unit.H,10*F,2);}
  equipmentOnHealthThreshold();
  skillOnHealthThreshold();

 }
 void incoming(int enemy);

 bool started=false,finished=false;long long executedTicks=0;
 int advance(int budget){
  if(battle&&!systemTick)throw runtime_error("Attached entities are advanced only by BattleSystem");
  if(budget<=0||finished)return 0;
  if(!started){started=true;
  gain(b.w(VOW,20,40)+20*b.n(MANAPOT),3,true);
  if(sc.z)shield((sc.z==2?.18:sc.z==4?.3:.4)*unit.H,10*F,1);
  for(size_t j=0;j<b.ids.size();j++)if(b.ids[j]>=0&&ITEMS[b.ids[j]].kind==CROWN)shield((ITEMS[b.ids[j]].rad?.5:.25)*unit.H,8*F,13+j);
  }
  const int begin=f,end=min(limit+1,f+budget);
  for(;f<end;f++){
  expireBuffs();
  if(output.config.enabled&&output.config.spellweaverUnits==4){auto range=equal_range(output.config.alliedSpellweaverCastFrames.begin(),output.config.alliedSpellweaverCastFrames.end(),f);for(auto it=range.first;it!=range.second;++it)buffs.addStack(BuffId::Spellweaver,1000000,BuffSource::Trait);}
  if(battle&&liveStunLease&&windupEnd>=f)++windupEnd;
  bool resolvedWindup=output.config.enabled&&windupEnd==f;
  if(resolvedWindup){states.release(windupLease);windupLease=0;windupEnd=-1;stats();resolveCast();}
   carryTick();
   if(f>=buffs.get(BuffId::Flail).end)buffs.get(BuffId::Flail).magnitude=0;stats();
   if(f){
    if(f<buffs.get(BuffId::Stasis).end){}else{
     double as=currentAttackSpeed();
     if((!battle||liveTargetAvailable)&&!states.blocked(CombatAction::Attack,f)&&!resolvedWindup&&(!output.config.enabled||output.alive()))unit.attackCharge+=as/F;
     while(unit.attackCharge>=1-EPS&&(!battle||liveTargetAvailable)&&!states.blocked(CombatAction::Attack,f)&&(!output.config.enabled||output.alive())){unit.attackCharge-=1;attack();if(output.config.enabled&&o.skills&&unit.mp>=unit.cap-EPS&&!states.blocked(CombatAction::Cast,f))cast();}
    }
    double regen=output.config.baseManaRegen+b.regen+(h.kind==23?(h.star==3?50:5):0)+(buffs.get(BuffId::Ascension).stacks?12*b.n(ASCENSION):0)+(equipment.covenantDied?10*b.n(COVENANT):0);
    if(!resolvedWindup)gain(regen/F,2);
    if(equipment.manazaneRemaining>0&&f>equipment.manazaneStart&&f>=states.castLockEnd&&!activeShieldManaLock()){gain(110.*b.n(MANAZANE)/(5*F),3);equipment.manazaneRemaining--;}
    if(equipment.manaPotRemaining>0&&f>equipment.potStart&&f>=states.castLockEnd&&!activeShieldManaLock()){gain(b.w(MANAPOT,80,90)/(5.*F),3);equipment.manaPotRemaining--;}
  tickPeriodicBuffs();
    if(f%F==0){
     skillOnSecond();
     heal(b.w(VISAGE,.02,.04)*(unit.H-unit.hp));
     for(int j=0;j<3;j++)if(f<burnEnd[j])deal(0,0,j); // burn is true damage; separately accounted below.
     for(int j=0;j<(output.config.enabled?0:3);j++)if(f<burnEnd[j]){double d=o.targetHP*burnRatio[j];if(output.config.enabled)d=output.apply(f,DamageSource::Equipment,"burn",0,0,output.config.target.maxHealth*burnRatio[j],1,1,0,0);r.damage+=d;if(o.itemVamp)heal(d*unit.sv,1);}
    }
  equipmentOnTick();
  if(!battle&&output.config.enabled&&outputBurnNext&&f>=outputBurnNext){
   if(f<=burnEnd[0])r.damage+=output.apply(f,DamageSource::Equipment,outputBurnSource.c_str(),0,0,output.config.target.maxHealth*burnRatio[0],1,1,0,0);
   outputBurnNext=f+F;
  }

   }
   if(o.skills&&unit.mp>=unit.cap-EPS&&!states.blocked(CombatAction::Cast,f))cast();
   if(!battle&&!output.config.enabled&&f&&f%hitInterval==0)incoming((f/hitInterval-1)%3);
   if(!r.alive){event("death",0);snapshot();break;}
   if(o.skills&&unit.mp>=unit.cap-EPS&&!states.blocked(CombatAction::Cast,f))cast();
   if(!battle){r.minHP=min(r.minHP,unit.hp);output.sample(f,F);snapshot();if(trace)event("frame");}
  }
  const int used=f-begin+(!r.alive?1:0);executedTicks+=used-(begin==0?1:0);
  if(r.alive&&f<=limit)return used;
  if(battle)return used;
  finished=true;
  finalize();return used;
 }
 void finalize(){
  r.hp=max(0.,unit.hp);r.H=unit.H;r.shield=totalShield();r.mana=unit.mp;r.debtLeft=max(0.,r.deferred-r.debtPaid-r.debtForgiven);
  assert(abs(r.mpInitial+r.mpGain-r.mpSpent-r.mana)<.001);
  assert(abs(r.granted-r.used-r.lost-r.shield)<.01+1e-10*max(r.granted,r.shield));
  assert(isfinite(r.H)&&isfinite(r.hp)&&isfinite(r.shield)&&isfinite(r.damage)&&isfinite(r.heal));
 }
 Result run();

// ---- combat/buffs.inc ----
 double totalShield()const{double z=0;for(int i=0;i<buffs.ns;i++)z+=buffs.shields[i].value;return z;}
 bool skillShield()const{for(int i=0;i<buffs.ns;i++)if(buffs.shields[i].tag==0&&buffs.shields[i].value>EPS)return true;return false;}
 bool activeShieldManaLock()const{return states.held(CombatAction::DirectMana);}
 void onShieldEnded(const Shield& effect,ShieldEndReason reason){
  states.release(effect.stateHandle);
  // Petrification keeps its explosion timing in skills; the restriction ends with its shield.
  if(effect.tag==0&&buffs.petrified)states.release(buffs.petrificationState);
  (void)reason;
 }
 void removeShield(int i,ShieldEndReason reason=ShieldEndReason::Removed){onShieldEnded(buffs.shields[i],reason);buffs.shields[i]=buffs.shields[--buffs.ns];}
 void shield(double v,int dur,int tag,double decay=0,StateMask restrictions=0,double armor=0,double magicResist=0){
  double before=capture?totalShield():0;
  double conv=min(1.,.4*b.n(IDOL))*v;if(conv){grow(conv*unit.healthFactor);r.converted+=conv;v-=conv;decay*=1-min(1.,.4*b.n(IDOL));}
  for(int i=0;i<buffs.ns;i++)if(buffs.shields[i].tag==tag){r.lost+=buffs.shields[i].value;presentationEvent("shieldReplace",buffs.shields[i].value,"sameTag");removeShield(i,ShieldEndReason::Replaced);break;}
  if(v>EPS){assert(buffs.ns<16);buffs.shields[buffs.ns++]={v,decay,f+dur,tag,tag==0?BuffSource::Skill:tag==12?BuffSource::PassiveSkill:tag<=2?BuffSource::Trait:BuffSource::Equipment,states.acquire(restrictions),armor,magicResist};r.granted+=v;presentationEvent("shieldGain",v,"grant");}
  if(capture&&before>EPS&&totalShield()<=EPS)presentationEvent("shieldBreak",0,"replacement");
 }
 void hot(double value,int frames,double physical=0,double magic=0,bool aoe=false){assert(buffs.nh<8);buffs.hots[buffs.nh++]={value/frames,physical/frames,magic/frames,f+frames,aoe,f};}
 void expireBuffs(){
   double beforeExpiry=capture?totalShield():0;
   for(int j=0;j<buffs.ns;){if(buffs.shields[j].end<=f){r.lost+=buffs.shields[j].value;presentationEvent("shieldExpire",buffs.shields[j].value,"duration");removeShield(j,ShieldEndReason::Expired);}else{if(f&&buffs.shields[j].decay){double take=min(buffs.shields[j].value,buffs.shields[j].decay);buffs.shields[j].value-=take;r.lost+=take;if(take>0)presentationEvent("shieldDecay",take,"decay");}if(buffs.shields[j].value<EPS)removeShield(j,ShieldEndReason::Broken);else j++;}}
   if(buffs.petrified&&!skillShield())endPetrification(o.malphiteBurstOnExpiry);
   if(capture&&beforeExpiry>EPS&&totalShield()<=EPS)presentationEvent("shieldBreak",0,"lifetime");
 }
 void tickPeriodicBuffs(){
    for(int j=0;j<buffs.nh;){auto z=buffs.hots[j];if(output.config.enabled&&f<=z.start){j++;continue;}heal(z.heal,2);if(z.aoe)aoe(z.physical,z.magic);else deal(z.physical,z.magic,0,true);if(f>=z.end)buffs.hots[j]=buffs.hots[--buffs.nh];else j++;}
 }

// ---- combat/skills.inc ----
 void grantSkillShield(double value,int duration,double armor=0,double magicResist=0){shield(value,duration,0,0,ShieldManaLock,armor,magicResist);}
 void cast(){
  if(!o.skills||carryPassiveOnly()||(battle&&!liveTargetAvailable))return;
  if(output.config.enabled){
   double speed=currentAttackSpeed();if(speed<=EPS||windupEnd>=0||!output.alive())return;
   long long ticks=max(1LL,static_cast<long long>(ceil(F/speed-1e-10))); // never resolve earlier than 1/AS
   double spent=unit.mp;r.casts++;if(output.config.spellweaverUnits==4)buffs.addStack(BuffId::Spellweaver,1000000,BuffSource::Trait);if(h.kind==CarryBlueSentry)spent=0;else{r.mpSpent+=unit.mp;unit.mp=0;}windupEnd=f+ticks;
   if(battle)submitCast(*this,spent);
   windupLease=states.acquire(stateBit(CombatAction::Attack)|stateBit(CombatAction::Mana)|stateBit(CombatAction::DirectMana)|stateBit(CombatAction::Cast));
   equipmentOnCast();stats();event("castStart",ticks);return;
  }
  double spent=unit.mp;r.casts++;if(output.config.spellweaverUnits==4)buffs.addStack(BuffId::Spellweaver,1000000,BuffSource::Trait);r.mpSpent+=unit.mp;unit.mp=0;states.castLockEnd=f+o.lock;if(h.kind!=12&&h.kind!=11)states.attackPauseEnd=f+o.pause;
  equipmentOnCast();stats();event("cast",r.casts);resolveCast();(void)spent;
 }
 void resolveCast(){
  if(isCarry()){event("castResolve",r.casts);carryResolveCast();return;}
  if(output.config.enabled)event("castResolve",r.casts);
  const auto& v=h.v;double ap=unit.lastAmp,ad=unit.lastAD;
  switch(h.kind){
   case 24:shield(v[0]*ap,4*F,0);buffs.petrified=true;states.release(buffs.petrificationState);buffs.petrificationState=states.acquire(stateBit(CombatAction::Cast)|(o.malphiteManaDuringShield?0:stateBit(CombatAction::Mana)));if(!o.malphiteAttacksDuringShield)states.attackPauseEnd=f+4*F;break;
   case 0:grantSkillShield(v[0]*ap,4*F);aoe(0,v[1]*ap);break;
   case 1:grantSkillShield(v[0]*ap,4*F);break; // Rakan ally AS is excluded by the fixed support-ally contract.
   case 2:deal(0,v[1]/100*defenses(true),0,true);stun(1.5,1);break;
   case 3:hot(.07*unit.H+v[0]*ap,2*F);states.castLockEnd=f+2*F;states.attackPauseEnd=f+2*F;skill.kobukoSmash=true;break;
   case 4:buffs.apply(BuffId::ReksaiHealing,f+3*F);aoe(0,v[1]*ap);stun(1);break;
   case 5:hot(v[1]*ap,3*F);buffs.apply(BuffId::DamageReduction,f+3*F,BuffSource::Skill,.15);states.castLockEnd=f+3*F;states.attackPauseEnd=f+3*F;break;
   case 6:heal(.08*unit.H+v[0]*ap,2);deal(0,v[2]*ap,0,true);stun(1.5,1);break;
   case 7:grantSkillShield(.1*unit.H+v[0]*ap,4*F);aoe(0,v[1]*ap);deal(0,v[2]*ap,0,true);break;
   case 8:grantSkillShield(v[0]*ap,4*F);buffs.setStacks(BuffId::ShenStrikes,3);break;
   case 9:if(!skill.transformed){skill.transformed=true;grow(v[0]*unit.healthFactor);}else buffs.apply(BuffId::SpiderHaste,f+4*F,BuffSource::Skill,1.75);break;
   case 10:heal(v[2]*ap,2);deal(v[1]*ad,0,0,true);break;
   case 11:hot(v[0]*ap,3*F);buffs.apply(BuffId::HecarimResistance,f+3*F,BuffSource::Skill,50);states.castLockEnd=f+3*F;aoe(0,v[1]*ap);stun(v[2]);break;
   case 12:heal(v[1]*ap,2);buffs.apply(BuffId::ViHaste,f+3*F,BuffSource::Skill,h.v[2]/100);buffs.apply(BuffId::DamageReduction,f+3*F,BuffSource::Skill,.15);break;
   case 13:for(int j=0;j<3;j++)flatM[j]+=10;hot(v[0]*ap,2*F,0,v[1]*ap,true);states.castLockEnd=f+2*F;states.directManaLockEnd=max(states.directManaLockEnd,f+2*F);states.attackPauseEnd=f+2*F;break;
   case 14:grow(v[1]*ap*unit.healthFactor);deal(v[2]*ad+.08*unit.H,0,0,true);break;
   case 15:grantSkillShield(v[1]*ap,2*F);aoe(0,2*v[0]*ap);break;
   case 16:grantSkillShield(v[0]*ap,4*F,60,60);break;
   case 17:grantSkillShield(.1*unit.H+v[0]*ap,4*F);aoe(0,v[1]*ap);break;
   case 18:heal(v[0]*ap,2);aoe(0,v[1]*ap);deal(0,v[1]*ap,0,true);stun(v[2]);break;
   case 19:aoe(0,v[2]*ap);stun(h.star==3?6:1);break;
   case 20:heal(.12*unit.H+v[0]*ap,2);aoe(v[1]*ad+.06*unit.H,0);break;
   case 21:deal(0,v[2]/100*unit.H,0,true);heal(v[3]*ap+(h.star==3?1:.1)*(unit.H-unit.hp),2);break;
   case 22:heal(v[1]*ap,2);buffs.setStacks(BuffId::TaricStrikes,2);break;
   case 23:if(!skill.transformed){skill.transformed=true;grow(v[2]*unit.healthFactor);unit.cap=max(15.,50.-10*b.n(DAWNCORE));for(int j=0;j<3;j++){flatA[j]+=v[1]*ap;flatM[j]+=v[1]*ap;}aoe(v[0]*ad,0);stun(1);}else {deal(v[3]*ad,0,0,true);for(int j=1;j<3;j++)deal(v[4]*ad,0,j,true,true,true);}break;
  }

 }
 void endPetrification(bool burst){if(!buffs.petrified)return;buffs.petrified=false;states.release(buffs.petrificationState);buffs.petrificationState=0;states.attackPauseEnd=min(states.attackPauseEnd,f);if(burst)aoe(0,h.v[1]*unit.lastAmp+h.v[2]*(defenses(true)+defenses(false)));}

 void skillAttackDamage(double& p,double& m){
  if(h.kind==5&&o.skills){p=h.v[0]*unit.lastAD*unit.critFactor;aoe(p,0,false);p=0;}
  if(h.kind==3&&skill.kobukoSmash&&o.skills){p=0;m+=.1*unit.H+h.v[1]*unit.lastAmp;skill.kobukoSmash=false;}
 }
 void skillOnAttack(){
  if(o.skills){
   if(h.kind==9&&skill.transformed){r.spiderAttacks++;heal(h.v[2]*unit.lastAmp,3);deal(0,h.v[1]*unit.lastAmp,0,true);}
   if(h.kind==12)heal(.02*unit.H,2);
   if(h.kind==8&&buffs.get(BuffId::ShenStrikes).stacks){deal(0,h.v[2]*unit.lastAmp,0,true);buffs.consume(BuffId::ShenStrikes);}
   if(h.kind==22&&buffs.get(BuffId::TaricStrikes).stacks){deal(0,h.v[2]*unit.lastAmp,0,true);buffs.consume(BuffId::TaricStrikes);}
  }
 }
 void skillOnHealthThreshold(){
  if(o.skills&&h.kind==22&&!skill.taric&&unit.hp<=.5*unit.H){skill.taric=true;shield((h.star==3?1:.15)*unit.H+h.v[0],(h.star==3?99:3)*F,12);}
  if(o.skills&&h.kind==20&&!skill.sett&&unit.hp<=.4*unit.H){skill.sett=true;gain(100,3,true);} }
 void skillAfterDamage(bool rammusBefore,double raw,double post){
  if(h.kind==21&&o.skills){skill.treeBlocked+=max(0.,raw-post);const double blockThreshold=h.star==3?300:650;while(skill.treeBlocked>=blockThreshold){skill.treeBlocked-=blockThreshold;deal(0,h.v[0]/100*unit.H,0,true);}}
  if(rammusBefore&&!skillShield()&&o.skills)aoe((o.resistanceMode?((unit.A+unit.extraA+buffs.get(BuffId::Mogul).stacks+60)*(o.resistanceMode&1?.7:1)+(unit.M+unit.extraM+buffs.get(BuffId::Mogul).stacks+60)*(o.resistanceMode&2?.7:1)):(unit.A+unit.M+unit.extraA+unit.extraM+2*buffs.get(BuffId::Mogul).stacks+120))*h.v[1]/100,0);
 }
 void skillOnSecond(){
     if(o.skills&&h.kind==19){heal((h.star==3?.04:.025)*unit.H+h.v[0]*unit.lastAmp,2);aoe(0,h.v[1]*unit.lastAmp);}
     if(o.skills&&h.kind==4)heal((.01*unit.H+h.v[0])*(f<buffs.get(BuffId::ReksaiHealing).end?3:1),2);
 }

// ---- combat/carry-skills.inc ----
 bool isCarry()const{return output.config.enabled&&h.kind>=CarryXayah&&h.kind<CarryEnd;}
 bool carryPassiveOnly()const{return isCarry()&&(h.kind==CarryCaitlyn||h.kind==CarryKayle||h.kind==CarryYi||h.kind==CarryYiAP);}
 double carryAttackSpeedBonus()const{
  if(!isCarry())return 0;
  double bonus=buffs.get(BuffId::CarryHaste).active(f)?buffs.get(BuffId::CarryHaste).magnitude:0;
  if(buffs.get(BuffId::CarryEmpower).stacks){if(h.kind==CarryShadowWolf)bonus+=1.75;if(h.kind==CarryAzir||h.kind==CarryNidalee)bonus+=1.5;}
  return bonus+(buffs.get(BuffId::XayahFeathers).stacks?.5:0)+buffs.get(BuffId::WarwickHaste).magnitude;
 }
 void carryResolveCast(){
  const auto& v=h.v;double ap=unit.lastAmp,ad=unit.lastAD;
  if(h.kind>CarryElderDragon){expandedResolveCast();return;}
  switch(h.kind){
   case CarryElderDragon:{
    if(!battle)throw runtime_error("Elder requires BattleSystem target effects");
    if(!carry.elderTransformed){
     if(output.config.elderFlightFrames<1)throw runtime_error("Explicit Elder flight duration required");
     carry.elderTransformed=true;stats();
     carry.elderFlightLease=states.acquire(stateBit(CombatAction::Attack)|stateBit(CombatAction::Cast)|stateBit(CombatAction::Mana)|stateBit(CombatAction::DirectMana)|stateBit(CombatAction::Untargetable));
     carry.elderLandFrame=f+output.config.elderFlightFrames;event("elderTakeoff",output.config.elderFlightFrames);
    }else{submitElderEffect(*this,false);deal(v[1]*ad+v[0]*ap,0,0,true);}
    break;
   }
   case CarryDraven:{
    double remaining=0;for(auto& w:buffs.dravenWounds)remaining+=w.perTick*w.remaining;
    buffs.dravenWounds.clear();
    for(int n=0;n<output.config.dravenAxeHits;n++)deal(v[1]*ad,0,0,true);
    if(remaining>0)deal(remaining,0,0,true); // consume remaining wound damage exactly once
    for(int n=0;n<output.config.dravenAxeHits;n++)carry.pending.push_back({f+max(1,output.config.dravenReturnFrames),v[2]*ad,0});
    break;
   }
   case CarryXayah:buffs.setStacks(BuffId::XayahFeathers,5);if(output.config.xayahEmpowerManaLock){states.release(carry.xayahLease);carry.xayahLease=states.acquire(stateBit(CombatAction::Mana)|stateBit(CombatAction::DirectMana)|stateBit(CombatAction::Cast));}break;
   case CarryWarwick:deal(v[0]*ad,0,0,true);buffs.get(BuffId::WarwickHaste).magnitude+=.2;break;
   case CarryVeigar:deal(0,(output.config.target.finite&&output.hp<.3*output.config.target.maxHealth?v[1]:v[0])*ap,0,true);break;
   case CarryAhri:deal(0,v[0]*ap,0,true);break; // fixed single target at explosion center
   case CarryKarma:{
    int duration=int(round(1.5*F));for(int t=1;t<=duration;t++)carry.pending.push_back({f+t,0,v[0]*ap/duration,false});
    carry.pending.push_back({f+duration,0,v[1]*ap});break;
   }
   case CarryAphelios:{
    int duration=2*F,count=max(1,int(v[0])+int(floor(max(0.,currentAttackSpeed()/h.as-1)/.2+EPS)));
    for(int n=1;n<=count;n++)carry.pending.push_back({f+int(ceil(double(n)*duration/count)),v[1]*ad,0});
    carry.pending.push_back({f+duration,v[3]*ad+v[2]*ap,0});
    states.release(carry.channelLease);carry.channelLease=states.acquire(stateBit(CombatAction::Attack)|stateBit(CombatAction::Mana)|stateBit(CombatAction::DirectMana)|stateBit(CombatAction::Cast));carry.channelEnd=f+duration;break;
   }
  }
 }
 void carryTick(){
  if(!isCarry())return;
  if(h.kind>CarryElderDragon)expandedTick();
  if(carry.elderFlightLease&&f>=carry.elderLandFrame){
   states.release(carry.elderFlightLease);carry.elderFlightLease=0;stats();event("elderLanding",0);
   submitElderEffect(*this,true);
   // Initial landing grants an immediate breath without a second mana payment/windup.
   deal(h.v[1]*unit.lastAD+h.v[0]*unit.lastAmp,0,0,true);
  }
  if(h.kind==CarryDraven){
   double due=0;for(size_t i=0;i<buffs.dravenWounds.size();){auto& w=buffs.dravenWounds[i];due+=w.perTick;if(--w.remaining==0)buffs.dravenWounds.erase(buffs.dravenWounds.begin()+i);else ++i;}
   if(due>0)deal(due,0,0,true,false,false,false);
  }
  if(carry.channelLease&&f>=carry.channelEnd){states.release(carry.channelLease);carry.channelLease=0;}
  for(size_t n=0;n<carry.pending.size();){auto hit=carry.pending[n];if(hit.frame<=f){deal(hit.physical,hit.magic,0,true,false,false,hit.needsTarget);carry.pending.erase(carry.pending.begin()+n);}else n++;}
 }
 void carryModifyAttack(double& p,double& m){
  if(!isCarry())return;
  if(h.kind>CarryElderDragon)expandedModifyAttack(p,m);
  if(h.kind==CarryDraven)p*=1+.5*min(1.,.12*unit.lastAmp);
  if(h.kind==CarryXayah&&buffs.get(BuffId::XayahFeathers).stacks)p=h.v[0]*unit.lastAD;
  if(h.kind==CarryCaitlyn&&r.attacks%3==0)p=h.v[1]*unit.lastAD+h.v[0]*unit.lastAmp;
 }
 void applyDravenWound(){
  if(h.kind!=CarryDraven)return;
  double layers=1+min(1.,.12*unit.lastAmp);
  buffs.dravenWounds.push_back({h.v[0]*unit.lastAD*layers/(12*F),12*F});
 }
 void carryAfterAttack(){
  if(!isCarry())return;
  if(h.kind>CarryElderDragon)expandedAfterAttack();
  if(h.kind==CarryDraven&&!battle)applyDravenWound();
  if(h.kind==CarryXayah&&buffs.get(BuffId::XayahFeathers).stacks){flatA[0]+=h.v[1]*unit.lastAmp;buffs.consume(BuffId::XayahFeathers);}
  if(h.kind==CarryKayle){
   if(h.star>=2){shredM[0]=max(shredM[0],.2);outputMagicShredEnd=max(outputMagicShredEnd,f+2*F);}
   deal(0,h.v[0]*unit.lastAmp,0,true);
   // Star-three wave hits OTHER units; absent in this single-target scenario.
  }
 }

 void carryAfterAttackMana(){if(carry.empowerLease&&!carry.bombEnd&&!buffs.get(BuffId::CarryEmpower).stacks){states.release(carry.empowerLease);carry.empowerLease=0;}if(carry.xayahLease&&!buffs.get(BuffId::XayahFeathers).stacks){states.release(carry.xayahLease);carry.xayahLease=0;}}

// ---- combat/expanded-carry-skills.inc ----
 int moonPhase()const{return (output.config.moonStartPhase+carry.moonCasts)%5;}
 bool cyclingMoon()const{return h.kind==CarryLunara&&output.config.moonCycle;}
 double moonReduction()const{return cyclingMoon()&&moonPhase()<=2?.07:0;}
 double moonAmplification()const{return cyclingMoon()&&moonPhase()>2?.07:0;}
 // Extended roster, single observed target. Explicit geometry assumptions live in OutputConfig.
 bool carryAPForm()const{return h.kind==CarryGromp||h.kind==CarryNidalee||h.kind==CarryAkaliAP||h.kind==CarryYiAP||h.kind==CarryKogmawAP;}
 double adaptorBonus()const{return output.config.adaptorUnits==2?.2:output.config.adaptorUnits==3?.3:output.config.adaptorUnits==4?.5:0;}
 double carryADBonus()const{return (carryAPForm()?0:adaptorBonus())+(buffs.get(BuffId::CarryAD).active(f)?buffs.get(BuffId::CarryAD).magnitude:0);}
 double carryAPBonus()const{return carryAPForm()?adaptorBonus():0;}
 double summonScale()const{return output.config.summonerUnits>=3?1.3:output.config.summonerUnits>=2?1.2:1;}
 void carryPeriodic(double p,double m,int duration,int interval=1,double ratio=0){
  if(duration<=0||interval<=0||duration%interval)throw runtime_error("Invalid periodic schedule");
  carry.periodic.push_back({f+interval,f+duration,interval,p,m,ratio});
 }
 void carryDot(double p,double m,int duration){carryPeriodic(p/duration,m/duration,duration);}
 void carryEmpower(int count){
  buffs.setStacks(BuffId::CarryEmpower,count);
  if(output.config.empoweredManaLock){states.release(carry.empowerLease);carry.empowerLease=states.acquire(stateBit(CombatAction::Mana)|stateBit(CombatAction::DirectMana)|stateBit(CombatAction::Cast));}
 }
 void carryHaste(double value,int end){buffs.apply(BuffId::CarryHaste,end,BuffSource::Skill,value);}
 void expandedResolveCast(){
  const auto& v=h.v;double ap=unit.lastAmp,ad=unit.lastAD;
  switch(h.kind){
   case CarryCamille:deal(v[1]*ad+v[0]*ap,0,0,true);grantSkillShield(v[2],2*F);break;
   case CarryAkali:deal(v[1]*ad+v[0]*ap+(targetBurning(*this)?v[2]*ad:0),0,0,true);break;
   case CarryAkaliAP:deal(0,v[0]*ap*(output.config.target.isTank?1.5:1),0,true);break;
   case CarryVarus:case CarryYunara:deal(v[1]*ad+v[0]*ap,0,0,true);break;
   case CarryBramble:deal(v[1]*ad+v[0]*ap,0,0,true);submitCarryEffect(*this,CarryEffectKind::Burn,.01,4*F);break;
   case CarryBlueSentry:
    states.release(carry.channelLease);carry.channelLease=states.acquire(stateBit(CombatAction::Attack)|stateBit(CombatAction::Cast)|(output.config.blueCanRegen?0:stateBit(CombatAction::Mana)|stateBit(CombatAction::DirectMana)));
    carry.channelEnd=limit+1;carry.blueEnd=f;break;
   case CarryShadowWolf:deal(v[1]*ad+v[0]*ap,0,0,true);carryEmpower(2);break;
   case CarryLeblanc:deal(0,v[1]*ap,0,true);break; // splash belongs to other targets
   case CarryGromp:deal(0,v[0]*ap,0,true);carryDot(0,v[1]*ap,3*F);break;
   case CarryGrompAD:deal(v[0]*ad+v[1]*ap+v[2]*ad,0,0,true);submitCarryEffect(*this,CarryEffectKind::Slow,.30,3*F);break;
   case CarryTeemo:deal(0,(2*v[0]+v[1])*ap,0,true);break; // two waves, one eligible target in each
   case CarryRengar:deal(v[0]*ad,0,0,true);heal((v[1]+(v[2]-v[1])*(1-unit.hp/unit.H))*ap,2);break;
   case CarryKhazix:deal(0,(output.config.targetIsolated?v[1]:v[0])*ap,0,true);if(output.config.targetIsolated)gain(10,3,true);break;
   case CarryTristana:
    carry.bombAttacks=0;carry.bombAD=ad;carry.bombEnd=f+4*F;carryHaste(.4+v[0]/100*ap,carry.bombEnd);
    states.release(carry.empowerLease);if(output.config.empoweredManaLock)carry.empowerLease=states.acquire(stateBit(CombatAction::Mana)|stateBit(CombatAction::DirectMana)|stateBit(CombatAction::Cast));break;
   case CarryRaptor:buffs.apply(BuffId::CarrySummons,f+max(1,int(round(v[0]*ap*F))));break;
   case CarryAzir:case CarryNidalee:carryEmpower(h.kind==CarryAzir?6:3);break;
   case CarryCassiopeia:carryDot(0,v[0]*ap,15*F);break;
   case CarryKogmaw:deal((v[1]*ad+v[0]*ap)*(output.hp<.5*output.config.target.maxHealth?1.4:1),0,0,true);break;
   case CarryKogmawAP:deal(0,v[0]*ap,0,true);carryDot(0,v[1]*ap,3*F);break;
   case CarryMorgana:
    deal(0,v[0]*ap,0,true);buffs.apply(BuffId::CarryCurse,f+4*F);carryPeriodic(0,(v[1]+v[2])*ap,4*F,F);break; // only this caster's one curse, no phantom teammates
   case CarryRedBuff:buffs.apply(BuffId::CarryAD,f+8*F,BuffSource::Skill,v[1]/100);break;
   case CarryNidaleeAD:{
    double factor=r.casts%3==0?1+1.25*(1-output.hp/output.config.target.maxHealth):1;
    deal(v[0]*ad*factor,0,0,true);if(r.casts%3==0)heal(v[1]*ap,2);break;
   }
   case CarryEzreal:
    if(r.casts%4==0){deal(v[2]*ad,0,0,true);carryHaste(0,0);}else{deal(v[0]*ad,0,0,true);carryHaste(buffs.get(BuffId::CarryHaste).magnitude+v[1]/100*ap,limit+1);}break;
   case CarrySivir:deal(v[1]*ad+v[0]*ap,0,0,true);break; // no second target => no bounce path
   case CarryZyra:{
    int count=10+(output.config.summonerUnits>=3?6:output.config.summonerUnits>=2?4:0),interval=output.config.plantAttackIntervalFrames;
    if(interval<=0)throw runtime_error("Zyra requires plant cadence");
    carryPeriodic(0,2*v[0]*ap,count*interval,interval);break;
   }
   case CarrySoraka:deal(0,(v[0]+(carry.marked?3*v[1]:0))*ap,0,true);carry.marked=true;break;
   case CarryKennen:{
    if(targetBurning(*this))ap+=.15;
    grantSkillShield(v[0]*ap,int(round(2.5*F)));deal(0,v[1]*ap,0,true);carryDot(0,v[2]*ap,2*F);break;
   }
   case CarryAshe:deal(v[0]*ad,0,0,true);carryPeriodic(v[2]*ad+v[1]*ap,0,4*F,F,v[3]/100);submitCarryEffect(*this,CarryEffectKind::Slow,.2,4*F);break;
   case CarryLunara:
    if(output.config.lunaraHitCount<=0||output.config.fullMoonEnemyCount<1)throw runtime_error("Lunara requires shard target allocation");
    event("moonPhaseAtCast",cyclingMoon()?moonPhase():output.config.fullMoon?4:0);
    deal(0,((cyclingMoon()?moonPhase()==4:output.config.fullMoon)?v[1]/output.config.fullMoonEnemyCount:output.config.lunaraHitCount*v[0])*ap,0,true);
    if(cyclingMoon()){++carry.moonCasts;stats();event("moonPhaseAfterCast",moonPhase());}break;
   case CarryLux:deal(0,v[0]*ap,0,true);gain(3*ap,3,true);break; // self shares own trait; no allied casts fabricated
   case CarryDiana:grantSkillShield(v[1]*ap,2*F);for(int i=0;i<6;i++)deal(0,v[0]*ap,0,true);break;
   case CarryGnar:
    if(!carry.gnarTransformed){carry.gnarTransformed=true;grow(v[2]*unit.healthFactor);unit.cap=max(15.,50.-10*b.n(DAWNCORE));flatA[0]+=v[1]*ap;flatM[0]+=v[1]*ap;deal(v[0]*ad,0,0,true);submitCarryEffect(*this,CarryEffectKind::Stun,0,F);}
    else if(output.config.gnarLastEnemy)submitCarryEffect(*this,CarryEffectKind::Remove,0,0);
    else deal(v[3]*ad,0,0,true);break;
   case CarryIvern:
    if(output.config.ivernTargetsSelf){grantSkillShield(v[0]*ap*unit.critFactor*unit.ampDamage,6*F);buffs.apply(BuffId::CarryAmplify,f+6*F,BuffSource::Skill,v[1]/100);if(r.casts>=6)carryHaste(buffs.get(BuffId::CarryHaste).magnitude+1,limit+1);deal(0,v[2]*ap,0,true);}break;
   default:throw runtime_error("Missing carry skill implementation");
  }
 }
 void expandedTick(){
  if(h.kind==CarryBlueSentry&&carry.channelLease&&f>carry.blueEnd){
   double spent=min(unit.mp,.35*unit.cap/F);unit.mp-=spent;r.mpSpent+=spent;
   flatM[0]+=3./F;deal(0,h.v[0]*unit.lastAmp/F,0,true,false,false,false);
   if(unit.mp<=EPS){states.release(carry.channelLease);carry.channelLease=0;carry.channelEnd=0;}
  }
  if(h.kind==CarryTristana&&carry.bombEnd&&f>=carry.bombEnd){
   deal((h.v[1]+carry.bombAttacks*h.v[2])*carry.bombAD,0,0,true,false,false,false);carry.bombEnd=0;states.release(carry.empowerLease);carry.empowerLease=0;
  }
  for(size_t i=0;i<carry.periodic.size();){auto& dot=carry.periodic[i];
   if(f>=dot.next&&f<=dot.end){deal(dot.physical+dot.healthRatio*output.config.target.maxHealth,dot.magic,0,true,false,false,false);dot.next+=dot.interval;}
   if(f>=dot.end)carry.periodic.erase(carry.periodic.begin()+i);else ++i;
  }
 }
 void expandedModifyAttack(double& p,double& m){
  if(buffs.get(BuffId::CarryEmpower).stacks){
   if(h.kind==CarryShadowWolf)p+=h.v[2]*unit.lastAD;
   if(h.kind==CarryAzir){p=0;m=2*h.v[0]*unit.lastAmp*summonScale();}
   if(h.kind==CarryNidalee){p=0;m=h.v[buffs.get(BuffId::CarryEmpower).stacks==1?1:0]*unit.lastAmp;}
  }
 }
 void expandedAfterAttack(){
  if(h.kind==CarryYi||h.kind==CarryYiAP){if(r.attacks%3==0){
   deal(h.ad*unit.lastAD,0,0,false); // extra strike does not recurse or create a second attack/mana event
   if(h.kind==CarryYi)carryHaste(buffs.get(BuffId::CarryHaste).magnitude+.12+h.v[0]/100*unit.lastAmp,limit+1);
   else deal(0,h.v[0]*unit.lastAmp,0,true);
  }}
  if(h.kind==CarryTristana&&carry.bombEnd>f)++carry.bombAttacks;
  if(h.kind==CarryRaptor&&buffs.get(BuffId::CarrySummons).active(f))for(int i=0;i<4;i++)deal(h.v[1]*unit.lastAD*summonScale(),0,0,true);
  if(h.kind==CarryShadowWolf||h.kind==CarryAzir||h.kind==CarryNidalee)buffs.consume(BuffId::CarryEmpower);
 }

// ---- combat/equipment.inc ----
 void equipmentOnCast(){
  if(b.n(DAWNCORE)&&r.casts>1)unit.cap=max(15.,unit.cap*pow(.95,b.n(DAWNCORE)));
  if(r.casts==1){equipment.manazaneRemaining=b.n(MANAZANE)?5*F:0;equipment.manazaneStart=f;equipment.manaPotRemaining=b.n(MANAPOT)?5*F:0;equipment.potStart=f;}
  buffs.setStacks(BuffId::LichStrikes,1,BuffSource::Equipment);
 }
 void equipmentOnAttack(){
  if(b.n(AXE))deal(o.axe*unit.H*b.n(AXE),0,0,false,true);
  if(b.n(HYDRA))aoe((.02*unit.H+.04*h.ad*unit.lastAD)*b.n(HYDRA),0,false,true);
  if(b.n(WITS)){double dmg[5]={25,45,65,85,100};deal(0,dmg[min(4,max(0,o.stage-2))]*b.n(WITS),0,false,true);}
  if(b.n(LICH)&&buffs.get(BuffId::LichStrikes).stacks){double dmg[5]={250,350,500,600,700};deal(0,dmg[min(4,max(0,o.stage-2))]*b.n(LICH),0,false,true);buffs.consume(BuffId::LichStrikes);}
  if(b.n(STATIKK)&&r.attacks%3==0)aoe(0,(15+.35*(unit.lastAmp-1)*100)*b.n(STATIKK),false,true);
  if(b.n(SILVERMERE))stun(.8,1);
  if(b.n(FLAIL)){buffs.get(BuffId::Flail).magnitude=min(4.,buffs.get(BuffId::Flail).magnitude+unit.crit);buffs.apply(BuffId::Flail,f+5*F,BuffSource::Equipment,buffs.get(BuffId::Flail).magnitude);}
 }
 void equipmentOnHealthThreshold(){
  if(!equipment.vow&&b.n(VOW)&&unit.hp<=.4*unit.H){equipment.vow=true;gain(b.w(VOW,15,30),3,true);bool normalGranted=false;for(size_t j=0;j<b.ids.size();j++)if(b.ids[j]>=0&&ITEMS[b.ids[j]].kind==VOW){if(!ITEMS[b.ids[j]].rad){if(normalGranted)continue;normalGranted=true;}shield((ITEMS[b.ids[j]].rad?.5:.2)*unit.H,limit,3+j);}}
  if(!equipment.blood&&b.n(BLOOD)&&unit.hp<=.5*unit.H){equipment.blood=true;bool normalGranted=false;for(size_t j=0;j<b.ids.size();j++)if(b.ids[j]>=0&&ITEMS[b.ids[j]].kind==BLOOD){if(!ITEMS[b.ids[j]].rad){if(normalGranted)continue;normalGranted=true;}shield((ITEMS[b.ids[j]].rad?.6:.3)*unit.H,5*F,6+j);}}
  if(!equipment.sterak&&b.n(STERAK)&&unit.hp<=.6*unit.H){equipment.sterak=true;for(size_t j=0;j<b.ids.size();j++)if(b.ids[j]>=0&&ITEMS[b.ids[j]].kind==STERAK){double ratio=ITEMS[b.ids[j]].rad?.8:.4;int duration=ITEMS[b.ids[j]].rad?6:4;shield(ratio*unit.H,duration*F,9+j,ratio*unit.H/(duration*F));}}
  if(!equipment.edge&&b.n(EDGE)&&unit.hp<=.4*unit.H){equipment.edge=true;heal((unit.H-unit.hp)*(b.c[EDGE][1]?1:1-pow(.85,b.c[EDGE][0])));buffs.apply(BuffId::EdgeInvulnerability,f+o.edgeFrames,BuffSource::Equipment);event("edge",o.edgeFrames);}
  if(!equipment.zhonya&&b.n(ZHONYA)&&unit.hp<=.4*unit.H){equipment.zhonya=true;buffs.apply(BuffId::Stasis,f+3*F,BuffSource::Equipment);states.attackPauseEnd=max(states.attackPauseEnd,buffs.get(BuffId::Stasis).end);states.stasisEnd=buffs.get(BuffId::Stasis).end;event("zhonya",3);}
  if(!equipment.healthPot&&b.n(HEALTHPOT)&&unit.hp<=.5*unit.H){equipment.healthPot=true;hot(b.w(HEALTHPOT,750,850),3*F);}
 }
 void equipmentOnTick(){
    if(f%(2*F)==0){heal(b.w(DCLAW,.025,.05)*unit.H);if(b.n(SUNFIRE)){int target=output.config.enabled?0:(f/(2*F)-1)%3;if(output.config.enabled)applyBurn(target,10*F,b.c[SUNFIRE][1]?.02:.01,"sunfire");else{burnEnd[target]=f+10*F;burnRatio[target]=max(burnRatio[target],b.c[SUNFIRE][1]?.02:.01);}}}
    if((aug&1)&&f%(10*F)==0)grow(16*b.c[STEADFAST][0]*unit.healthFactor);
    if(b.n(LIGHTSHIELD)&&f%(3*F)==0)shield(.7*(defenses(true)+defenses(false))*b.n(LIGHTSHIELD),5*F,16);
    if(b.n(DAWN)||b.n(DUSK)){
     double interval=(b.n(DAWN)&&b.n(DUSK)?1.25:2.5)*F;
     if(int(f/interval)>int((f-1)/interval)){
      for(int j=0;j<3;j++){double sa=min(3.*b.n(DAWN),max(0.,enemyA[j]-flatA[j]));double sm=min(3.*b.n(DUSK),max(0.,enemyM[j]-flatM[j]));unit.extraA+=sa;unit.extraM+=sm;flatA[j]+=sa;flatM[j]+=sm;}
      if(b.n(DAWN))heal(o.dawn*defenses(true)*b.n(DAWN));
      if(b.n(DUSK))aoe(0,.18*defenses(false)*b.n(DUSK),false,true);
     }
    }
    if(b.n(ASCENSION)&&!buffs.get(BuffId::Ascension).stacks&&f>=22*F){buffs.get(BuffId::Ascension).stacks=1;double add=(unit.H/unit.healthFactor)*b.n(ASCENSION);unit.healthFactor+=b.n(ASCENSION);grow(add);}
    if(b.n(COVENANT)){
     if(!equipment.covenantDied&&f>=o.allyDeath){equipment.covenantDied=true;unit.bonusAP+=.4*b.n(COVENANT);}
     if(!equipment.covenantDied&&o.allyPeriod>0&&f%o.allyPeriod==0)gain(15*b.n(COVENANT),3);
    }
    // Target dummies cast an 80-mana spell every four seconds, for Ionic's documented trigger.
    if(!output.config.enabled&&b.n(IONIC)&&f%(4*F)==0)aoe(0,b.w(IONIC,1.5,3)*80,false,true);
    if(b.n(BOMBPOT)&&f==8*F)stun(b.c[BOMBPOT][1]?2:1.75);
    if(b.n(DEFY)){
     equipment.debtRate+=equipment.debtChanges[f%(4*F+1)];equipment.debtChanges[f%(4*F+1)]=0;
     double due=max(0.,equipment.debtRate);double d=f>=buffs.get(BuffId::Stasis).end?min(max(0.,unit.hp-1),due):0;unit.hp-=d;refreshHealthBuffs();r.debtPaid+=d;if(d>0)presentationEvent("damage",d,"deferred");r.debtForgiven+=due-d;trigger();
    } }
 void equipmentAfterDamage(){
  if(b.n(BRAMBLE)&&f>=equipment.brambleReady){aoe(0,b.w(BRAMBLE,100,200),false,true);equipment.brambleReady=f+2*F;}
 }

// ---- combat/attributes.inc ----
 HealthBand healthBand()const{return unit.hp<unit.H*.5?HealthBand::Below:unit.hp>unit.H*.5?HealthBand::Above:HealthBand::Half;}
 // HP writers notify synchronously, before any subsequent damage/heal in this frame.
 void refreshHealthBuffs(){if(b.n(JUSTICE)&&buffs.justiceBand!=healthBand())stats();}
 double spiritBlossomBonus()const{return output.config.spiritBlossomUnits==3?.12:0;}
 double lunarBonus()const{return output.config.lunarUnits==2?.14:0;} // member gets twice the 7% aura
 double hunterAD()const{return !output.config.enabled?0:output.config.hunterUnits==2?.20:output.config.hunterUnits==3?.30:output.config.hunterUnits==4?.45:output.config.hunterUnits==5?.65:0;}
 double rapidfireAS()const{return output.config.enabled&&output.config.rapidfireUnits==3?.10+.05*buffs.get(BuffId::Rapidfire).stacks:0;}
 double spellweaverAP()const{return output.config.enabled&&output.config.spellweaverUnits==4?.10+.30+.01*buffs.get(BuffId::Spellweaver).stacks:0;}
 double slayerBonus(double targetHP,double targetMaxHP)const{return output.config.enabled&&output.config.slayerUnits==4?.25*(targetHP<.5*targetMaxHP?2:1):0;}
 double abilityPowerMultiplier()const{
  double justice=b.w(JUSTICE,.18,.35)*(healthBand()==HealthBand::Above?2:1);
  double blue=1+b.w(BLUE,.10,.20);
  return (1+spiritBlossomBonus()+lunarBonus()+spellweaverAP()+carryAPBonus()+b.ap+unit.bonusAP+justice+b.n(HULL)*.1+(h.role==2?b.w(HELM,.1,.4):0)+b.w(ARCHANGEL,.20,.40)*(f/(5*F))+(f>=8*F?b.w(CROWN,.25,.50):0)+b.w(TITAN,.02,.04)*buffs.get(BuffId::Titan).stacks+b.n(FLICKER)*.02*(r.attacks/3))*blue;
 }
 void stats(){
  buffs.justiceBand=healthBand();
  double justice=b.w(JUSTICE,.18,.35)*(healthBand()==HealthBand::Above?2:1);
  double blue=1+b.w(BLUE,.10,.20);
  unit.lastAmp=abilityPowerMultiplier();
  unit.lastAD=(1+spiritBlossomBonus()+hunterAD()+carryADBonus()+b.ad+unit.bonusAD+justice+b.n(HULL)*.1+(h.role==2?b.w(HELM,.1,.4):0)+b.w(TITAN,.02,.04)*buffs.get(BuffId::Titan).stacks+b.w(KRAKEN,.035,.07)*min(15,r.attacks)+b.n(FLICKER)*.02*(r.attacks/3))*blue;
  const int retribution=b.n(JUSTICE)>0?1:0;double cc=.25+b.crit+.25*retribution+(output.config.executionerUnits>=2?.15:0);unit.crit=min(1.,cc);unit.critFactor=1+unit.crit*(.4+b.critmult+.5*max(0.,cc-1)+.1*max(0,b.n(IE)+b.n(JG)+retribution-1));unit.spellCrit=b.n(IE)+b.n(JG)+retribution||output.config.executionerUnits>=2?unit.critFactor:1;
  unit.sv=(h.kind==CarryMorgana?.25:0)+(output.config.enabled&&output.config.slayerUnits==4?.10:0)+(carry.elderTransformed?.15:0)+b.sv+b.w(JUSTICE,.15,.30)*(buffs.justiceBand==HealthBand::Below?2:1);
  unit.ampDamage=1+moonAmplification()+(buffs.get(BuffId::CarryAmplify).active(f)?buffs.get(BuffId::CarryAmplify).magnitude:0)+b.da+(hunterAD()>0&&f>=3*F?.10:0)+(output.config.enabled&&output.config.target.isTank?b.w(GIANTSLAYER,.15,.30):0)+(buffs.get(BuffId::Ascension).stacks?1.2*b.n(ASCENSION):0)+(buffs.get(BuffId::Titan).stacks>=25?b.w(TITAN,.10,.20):0)+b.w(FLAIL,.05,.10)*buffs.get(BuffId::Flail).magnitude;
 }
 double defenses(bool armor){
  double v=(armor?unit.A:unit.M)+(armor?unit.extraA:unit.extraM)+buffs.get(BuffId::Mogul).stacks;
  v+=(f<15*F?b.c[EVENSHROUD][0]*15:0)+(f<20*F?b.c[EVENSHROUD][1]*50:0);
  if(o.skills&&h.kind==2)v+=h.v[0]*unit.lastAmp*max(0.,1-double(f)/(12*F));
  if(o.skills){if(f<buffs.get(BuffId::HecarimResistance).end)v+=buffs.get(BuffId::HecarimResistance).magnitude;v+=buffs.shieldResistance(armor);}
  return v>0&&((armor?1:2)&o.resistanceMode)?v*.7:v;
 }

};

// ---- combat/settlement.inc ----
// Called only by BattleSystem (or its historical fixed-pressure adapter).
struct CombatSettlement {
 friend struct BattleSystem;
 private:
 static void stun(HeroEntity& target,int frames){
  if((target.b.n(QSS)&&target.f<18*target.F)||(target.b.n(TITAN)&&target.buffs.get(BuffId::Titan).stacks>=25))return;
  if(!target.liveStunLease)target.liveStunLease=target.states.acquire(stateBit(CombatAction::Attack)|stateBit(CombatAction::Cast));
  target.liveStunEnd=max(target.liveStunEnd,target.f+frames);target.event("stun",frames);
 }
 static double execute(HeroEntity& target,double threshold,const char* source="elder"){
  if(!target.r.alive||target.cannotDie||target.unit.hp>=threshold*target.unit.H)return 0;
  double lost=max(0.,target.unit.hp);target.unit.hp=0;target.refreshHealthBuffs();target.r.alive=false;target.r.frame=target.f;
  target.presentationEvent("execute",lost,source);target.event("execute",lost);return lost;
 }
 static double heal(HeroEntity& target,double v,int src){v=max(0.,v);if(!target.b.n(MITTENS)&&target.f>=target.o.woundStart&&target.f<target.o.woundEnd)v*=1-target.o.wound;if(target.battle&&target.f<target.liveWoundEnd)v*=1-max(0.,.33-((target.f>=target.o.woundStart&&target.f<target.o.woundEnd)?target.o.wound:0.))/(1-((target.f>=target.o.woundStart&&target.f<target.o.woundEnd)?target.o.wound:0.));double actual=min(max(0.,target.unit.H-target.unit.hp),v);target.unit.hp+=actual;target.refreshHealthBuffs();target.r.heal+=actual;target.r.overheal+=v-actual;if(src==1)target.r.vamp+=actual;if(src==2)target.r.skillHeal+=actual;if(src==3)target.r.spiderHeal+=actual;if(actual>0)target.presentationEvent("heal",actual,src==1?"lifesteal":src==2?"skill":src==3?"spider":"other");return actual;}
 static void gain(HeroEntity& target,double v,int src,bool bypass){
  if(v<=0)return;v*=1+target.b.w(HELM,.15,.30);
  if(target.states.blocked(bypass?CombatAction::DirectMana:CombatAction::Mana,target.f)){target.r.mpBlocked+=v;return;}
  double actual=min(v,max(0.,target.unit.cap-target.unit.mp));target.unit.mp+=actual;target.r.mpGain+=actual;target.r.mpOverflow+=v-actual;
  if(src==0)target.r.mpAttack+=actual;else if(src==1)target.r.mpDamage+=actual;else if(src==2)target.r.mpRegen+=actual;else target.r.mpSpecial+=actual;
  if(target.trace)target.event("mana"+to_string(src),actual);
 }

 static double receive(HeroEntity& target,double raw,int enemy,const DamageRequest* packet=nullptr,double armorShred=0){
  if(!target.r.alive)return 0;

  target.r.raw+=raw;
  if(target.f<target.buffs.get(BuffId::EdgeInvulnerability).end||target.f<target.buffs.get(BuffId::Stasis).end){target.r.avoided+=raw;return 0;}
  if(target.f<target.enemyStun[enemy]){target.r.ccAvoided+=raw;return 0;}
  double jug=target.sc.jug==2?.2:target.sc.jug==4?.33:target.sc.jug==6?.45:0;
  double mul=target.b.dr*(1-target.moonReduction())*(1-jug)*((target.aug&2)?.85:1)*pow(target.unit.hp>.5*target.unit.H?.85:.95,target.b.c[STEADFAST][0])*pow(target.unit.hp>.5*target.unit.H?.7:.9,target.b.c[STEADFAST][1]);
  if(target.sc.z==6&&target.buffs.ns)mul*=.95;if(target.f<target.buffs.get(BuffId::DamageReduction).end)mul*=1-target.buffs.get(BuffId::DamageReduction).magnitude;
  double dmg;
  if(packet){
   double ar=(target.defenses(true)-packet->flatArmor)*(1-target.liveArmorShred),mr=(target.defenses(false)-packet->flatMR)*(1-target.liveMRShred);
   if(ar>0)ar*=1-packet->armorPenetration;
   double attackReduction=(!packet->spell&&!packet->item)?pow(.95,target.b.c[BRAMBLE][0])*pow(.90,target.b.c[BRAMBLE][1]):1;
   dmg=((packet->physical*target.res(ar)+packet->magic*target.res(mr))*packet->crit*packet->amp*attackReduction)*mul+packet->pure;
  }else {dmg=(target.o.physicalShare==.5?raw*.5*(pow(.95,target.b.c[BRAMBLE][0])*pow(.90,target.b.c[BRAMBLE][1])*target.res(target.defenses(true))+target.res(target.defenses(false))):raw*(target.o.physicalShare*pow(.95,target.b.c[BRAMBLE][0])*pow(.90,target.b.c[BRAMBLE][1])*target.res(target.defenses(true))+(1-target.o.physicalShare)*target.res(target.defenses(false))))*mul;}

  double post=dmg;bool rammusBefore=target.h.kind==16&&target.skillShield();bool malphiteBefore=target.h.kind==24&&target.buffs.petrified&&target.skillShield();
  double usedBefore=target.capture?target.r.used:0,shieldBefore=target.capture?target.totalShield():0;
  // Expiring shields absorb first. At most 16, no heap allocation in the inner loop.
  while(dmg>EPS&&target.buffs.ns){int k=0;for(int j=1;j<target.buffs.ns;j++)if(target.buffs.shields[j].end<target.buffs.shields[k].end)k=j;double take=min(dmg,target.buffs.shields[k].value);target.buffs.shields[k].value-=take;dmg-=take;target.r.used+=take;if(target.buffs.shields[k].value<EPS)target.removeShield(k,ShieldEndReason::Broken);}
  if(target.capture&&target.r.used>usedBefore)target.presentationEvent("shieldAbsorb",target.r.used-usedBefore,"incoming");
  if(target.capture&&shieldBefore>EPS&&target.totalShield()<=EPS)target.presentationEvent("shieldBreak",0,"damage");
  if(target.b.n(DEFY)&&dmg>0){double deferred=.5*dmg;dmg-=deferred;double rate=deferred/(4*target.F);target.equipment.debtRate+=rate;target.equipment.debtChanges[(target.f+4*target.F+1)%(4*target.F+1)]-=rate;target.r.deferred+=deferred;}
  if(dmg>0)target.presentationEvent("damage",min(max(0.,target.unit.hp),dmg),"incoming");
  double effective=post-dmg+min(max(0.,target.unit.hp),dmg);
  if(target.cannotDie)effective=post; // immortal receiver still supplies damage/lifesteal
  target.unit.hp-=dmg;
  if(target.cannotDie)target.unit.hp=max(1.,target.unit.hp);target.refreshHealthBuffs();
  if(target.unit.hp<=0){target.r.alive=false;target.r.frame=target.f;return effective;}
  if(malphiteBefore&&!target.skillShield())target.endPetrification(true);
  if(target.h.role==0)target.gain(min(42.5,.01*raw+target.o.post*(target.o.shieldMana?post:dmg)),1);
  if(target.b.n(MOGUL)&&target.buffs.get(BuffId::Mogul).stacks<35){target.buffs.get(BuffId::Mogul).stacks++;target.grow(5*target.unit.healthFactor);}
  if(target.b.n(TITAN))target.buffs.addStack(BuffId::Titan,25);
  target.skillAfterDamage(rammusBefore,raw,post);
  if(!packet||(!packet->spell&&!packet->item))target.equipmentAfterDamage();
  target.trigger();target.event("incoming",post);
  return effective;
 }
};

// ---- combat/battle-system.inc ----
// Stable ids, not vector traversal order, define same-frame initiative.
struct BattleSystem {
 vector<HeroEntity*> entities;
 struct CarryEffect {int source,target;CarryEffectKind kind;double value;int duration;};
 vector<CarryEffect> carryEffects;
 bool mechanicalVictory=false;
 void carryEffect(HeroEntity& e,CarryEffectKind kind,double value,int duration){carryEffects.push_back({e.entityId,opponent(e).entityId,kind,value,duration});}

 vector<DamageRequest> pending;
 // Scenario routing: attacks can be directed outside this observed duel.
 // Exclusion happens before settlement, so it grants no on-hit, taken-hit or vamp effects.
 vector<int> excludedDamageTargets;
 struct Hit {int frame,source,target;double raw,dealt,hp,shield;};
 vector<Hit> hits;
 int frame=0,fps=30,maxFrame=0;unsigned long long sequence=0;
 bool ended=false;bool retainHits=true;
 enum class BurnChannel {Ordinary,Inferno};
 struct Burn {int source=-1,target=-1,next=0,end=0;double ratio=0;BurnChannel channel=BurnChannel::Ordinary;};
 vector<Burn> burns;
 // A rolling sum of independent 3-second bleeds: new hits never erase unfinished damage.
 struct ExecutionerBleed {int source,target;double rate=0;vector<double> expires;};
 vector<ExecutionerBleed> executionerBleeds;
 void addExecutionerBleed(HeroEntity& source,HeroEntity& target,double value){
  int duration=3*fps;double rate=value/duration;
  for(auto& b:executionerBleeds)if(b.source==source.entityId&&b.target==target.entityId){b.rate+=rate;b.expires[(frame+duration+1)%(duration+1)]+=rate;return;}
  ExecutionerBleed b{source.entityId,target.entityId,rate,vector<double>(duration+1)};b.expires[(frame+duration+1)%(duration+1)]=rate;executionerBleeds.push_back(std::move(b));
 }

 struct ElderEffect {int source,target;bool landing;};vector<ElderEffect> elderEffects;
 struct Ignite {int source,target,next,end;};vector<Ignite> ignites;
 void elderEffect(HeroEntity& source,bool landing){elderEffects.push_back({source.entityId,opponent(source).entityId,landing});}

 HeroEntity& opponent(HeroEntity& e){if(entities.size()!=2)throw runtime_error("Two entities required");return *(entities[0]==&e?entities[1]:entities[0]);}
 static double infernoRatio(int units){
  switch(units){case 0:return 0;case 2:case 3:return .01;case 5:return .035;case 7:return .045;default:throw runtime_error("Unsupported Inferno tier");}
 }
 void burn(HeroEntity& source,HeroEntity& target,int duration,double ratio,BurnChannel channel=BurnChannel::Ordinary){
  target.liveWoundEnd=max(target.liveWoundEnd,frame+duration);
  for(auto& b:burns)if(b.target==target.entityId&&b.channel==channel){if(frame>b.end){b={source.entityId,target.entityId,frame+fps,frame+duration,ratio,channel};}else{b.end=max(b.end,frame+duration);if(ratio>=b.ratio){b.ratio=ratio;b.source=source.entityId;}}return;}
  burns.push_back({source.entityId,target.entityId,frame+fps,frame+duration,ratio,channel});
 }
 void cast(HeroEntity& caster,double spent){auto& enemy=opponent(caster);if(enemy.b.n(IONIC))request(enemy,0,enemy.b.w(IONIC,1.5,3)*spent,false,true,false);}

 void add(HeroEntity& e,int id){
  infernoRatio(e.output.config.infernoUnits);
  if(e.output.config.spiritBlossomUnits!=0&&e.output.config.spiritBlossomUnits!=3)throw runtime_error("Unsupported Spirit Blossom baseline");
  if(e.output.config.lunarUnits!=0&&e.output.config.lunarUnits!=2)throw runtime_error("Unsupported Lunar baseline");
  if(e.output.config.executionerUnits<0||e.output.config.executionerUnits==1||e.output.config.executionerUnits>4)throw runtime_error("Unsupported Executioner tier");
  if(e.battle||e.started)throw runtime_error("Entity already attached or started");
  if(!entities.empty()&&(e.F!=fps||e.limit!=maxFrame))throw runtime_error("Battle clocks must match");
  for(auto* other:entities)if(other->entityId==id)throw runtime_error("Duplicate entity id");
  if(e.h.kind!=12&&!(e.h.kind>=CarryXayah&&e.h.kind<CarryEnd))throw runtime_error("Live duel hero not yet supported");
  if(e.h.kind>CarryElderDragon){
   if(!e.output.config.expandedScenario)throw runtime_error("Expanded hero requires explicit scenario assumptions");
   if(e.h.kind==CarryZyra&&e.output.config.plantAttackIntervalFrames<=0)throw runtime_error("Zyra plant cadence not specified");
   if(e.h.kind==CarryLunara&&e.output.config.moonCycle&&(e.output.config.fullMoon||e.output.config.moonStartPhase<0||e.output.config.moonStartPhase>4))throw runtime_error("Invalid moon cycle");
   if(e.h.kind==CarryLunara&&e.output.config.lunaraHitCount<=0)throw runtime_error("Lunara hit allocation not specified");
  }
  if(e.h.kind==CarryElderDragon&&e.output.config.elderFlightFrames<1)throw runtime_error("Elder flight duration must be explicitly configured");
  for(int index:e.b.ids)if(index>=0&&(ITEMS[index].cat!=0||ITEMS[index].rad||ITEMS[index].kind==FLAIL))throw runtime_error("Live duel excludes non-normal items and Flail");
  if(!e.output.config.enabled)throw runtime_error("Live entity requires output action timing");
  e.battle=this;e.entityId=id;fps=e.F;maxFrame=e.limit;entities.push_back(&e);
  sort(entities.begin(),entities.end(),[](auto*a,auto*b){return a->entityId<b->entityId;});
 }
 HeroEntity& find(int id){for(auto*e:entities)if(e->entityId==id)return *e;throw runtime_error("Unknown entity");}
 void request(HeroEntity& source,double p,double m,bool spell,bool item,bool aoe,bool needsTarget=true){
  if(entities.size()!=2)throw runtime_error("Live battle currently requires exactly two entities");
  auto* target=entities[0]==&source?entities[1]:entities[0];
  DamageRequest packet{source.entityId,target->entityId,frame,sequence++,p,m,spell?source.unit.spellCrit:item?1:source.unit.critFactor,item?1:source.unit.ampDamage,(!item||source.o.itemVamp)?source.unit.sv:0,spell,item,aoe};
  packet.needsTarget=needsTarget;packet.flatArmor=source.flatA[0];packet.flatMR=source.flatM[0];packet.innateMRShred=(source.f<source.outputMagicShredEnd)?source.shredM[0]:0;
  if(source.h.kind==CarryRedBuff&&source.buffs.get(BuffId::CarryAD).active(frame))packet.armorPenetration=min(1.,.20+.25*source.unit.lastAmp);
  if(source.h.kind==CarryNidaleeAD&&spell&&!item)packet.armorPenetration=.40;
  pending.push_back(packet);
 }
 static double heal(HeroEntity& entity,double value,int source){return CombatSettlement::heal(entity,value,source);}
 static void mana(HeroEntity& entity,double value,int source,bool bypass){CombatSettlement::gain(entity,value,source,bypass);}
 static void fixedIncoming(HeroEntity& target,int enemy){CombatSettlement::receive(target,target.o.dps/target.o.frequency,enemy);}
 void tick(){
  if(ended)return;
  if(entities.size()!=2)throw runtime_error("Live battle requires exactly two entities");
  for(auto*e:entities){
   if(e->liveStunLease&&frame>=e->liveStunEnd){e->states.release(e->liveStunLease);e->liveStunLease=0;}
   auto& enemy=opponent(*e);e->liveTargetAvailable=!enemy.states.held(CombatAction::Untargetable);e->output.config.target.finite=true;e->output.config.target.maxHealth=enemy.unit.H;e->output.hp=enemy.unit.hp;e->output.config.target.isTank=enemy.h.role==0;
   if(frame>=e->liveArmorShredEnd)e->liveArmorShred=0;
   if(frame>=e->liveMRShredEnd)e->liveMRShred=0;
   e->liveArmorShred=max(e->liveArmorShred,e->fixedArmorShred);e->liveMRShred=max(e->liveMRShred,e->fixedMRShred);
   if(enemy.b.n(EVENSHROUD))e->liveArmorShred=max(e->liveArmorShred,.3);
   if(enemy.b.n(IONIC))e->liveMRShred=max(e->liveMRShred,.3);
  }
  // Both actors produce intents before cross-entity damage mutates either actor.
  for(auto*e:entities){if(e->f!=frame)throw runtime_error("Entity clock drift");e->systemTick=true;e->advance(1);e->systemTick=false;e->f=frame;}
  for(auto& effect:carryEffects){auto& source=find(effect.source);auto& target=find(effect.target);
   if(!source.r.alive||!target.r.alive)continue;
   if(effect.kind==CarryEffectKind::Slow){auto& slow=target.buffs.get(BuffId::CarrySlow);if(!slow.active(frame))slow.magnitude=0;slow.magnitude=max(slow.magnitude,effect.value);slow.end=max(slow.end,frame+effect.duration);}
   if(effect.kind==CarryEffectKind::Stun)CombatSettlement::stun(target,effect.duration);
   if(effect.kind==CarryEffectKind::Burn)burn(source,target,effect.duration,effect.value);
   if(effect.kind==CarryEffectKind::Remove&&!target.cannotDie){target.r.alive=false;target.r.frame=frame;mechanicalVictory=true;target.event("removedFromBattle",0);}
  }carryEffects.clear();
  for(auto& effect:elderEffects){auto& source=find(effect.source);auto& target=find(effect.target);
   if(!source.r.alive||!target.r.alive)continue;
   if(effect.landing)CombatSettlement::stun(target,int(ceil(1.25*fps)));
   bool found=false;for(auto& ignite:ignites)if(ignite.source==effect.source&&ignite.target==effect.target){if(frame>ignite.end)ignite.next=frame+fps;ignite.end=frame+3*fps;found=true;break;}
   if(!found)ignites.push_back({effect.source,effect.target,frame+fps,frame+3*fps});
  }elderEffects.clear();
  for(auto& ignite:ignites)if(frame>=ignite.next&&frame<=ignite.end){auto& source=find(ignite.source);auto& target=find(ignite.target);
   DamageRequest hit{ignite.source,ignite.target,frame,sequence++,.02*target.unit.H,0,source.unit.spellCrit,source.unit.ampDamage,source.unit.sv,true,false,false};hit.needsTarget=false;pending.push_back(hit);ignite.next=frame+fps;
  }
  for(auto*e:entities){
   if(frame>0&&frame%(2*fps)==0&&e->b.n(SUNFIRE))burn(*e,opponent(*e),10*fps,.01);
  }
  for(auto& b:burns)if(frame>=b.next&&frame<=b.end){auto& target=find(b.target);DamageRequest hit{b.source,b.target,frame,sequence++,0,0,1,1,0,false,true,false};hit.needsTarget=false;hit.pure=target.unit.H*b.ratio;pending.push_back(hit);b.next=frame+fps;}
  for(auto& b:executionerBleeds){
   int slot=frame%int(b.expires.size());b.rate=max(0.,b.rate-b.expires[slot]);b.expires[slot]=0;
   if(b.rate>EPS){DamageRequest hit{b.source,b.target,frame,sequence++,0,0,1,1,0,false,true,false};hit.needsTarget=false;hit.pure=b.rate;pending.push_back(hit);}
  }
  for(size_t i=0;i<pending.size();++i){
   if(i>10000)throw runtime_error("Unbounded same-frame effect chain");
   auto packet=pending[i];auto& source=find(packet.source);auto& target=find(packet.target);
   if(std::find(excludedDamageTargets.begin(),excludedDamageTargets.end(),packet.target)!=excludedDamageTargets.end())continue;
   // An actor killed by an earlier same-frame hit loses its pending actions.
   if(!source.r.alive||!target.r.alive)continue;
   if((packet.needsTarget&&target.states.held(CombatAction::Untargetable))||(source.liveStunLease&&packet.needsTarget))continue;
   // Resolve the health threshold per packet, including earlier damage/healing this tick.
   if(!packet.item)packet.amp+=source.slayerBonus(target.unit.hp,target.unit.H);
   double raw=(packet.physical+packet.magic)*packet.crit*packet.amp+packet.pure;
   if(!packet.item&&source.b.n(LASTWHISPER)){target.liveArmorShred=max(target.liveArmorShred,.3);target.liveArmorShredEnd=frame+3*fps;}
   if(!packet.item&&source.b.n(VOIDSTAFF)){target.liveMRShred=max(target.liveMRShred,.3);target.liveMRShredEnd=frame+5*fps;}
   if(packet.innateMRShred>0){target.liveMRShred=max(target.liveMRShred,packet.innateMRShred);target.liveMRShredEnd=max(target.liveMRShredEnd,frame+2*fps);}
   double dealt=CombatSettlement::receive(target,raw,0,&packet);
   // Declared model: 30/40% of settled attack/skill damage, including shield absorption,
   // paid over the next 3 seconds at battle tick cadence. Item/bleed packets cannot recurse.
   if(dealt>0&&!packet.item&&source.output.config.executionerUnits>=3)
    addExecutionerBleed(source,target,dealt*(source.output.config.executionerUnits==4?.40:.30));
   if(dealt>0&&!packet.item&&(source.b.n(RED)||source.b.n(MORELLO)))burn(source,target,(source.b.n(MORELLO)?10:5)*fps,.01);
   // Item/DOT packets do not refresh themselves or recursively create another burn.
   if(dealt>0&&!packet.item&&source.output.config.infernoUnits)burn(source,target,3*fps,infernoRatio(source.output.config.infernoUnits),BurnChannel::Inferno);
   if(dealt>0&&source.h.kind==CarryDraven&&!packet.spell&&!packet.item)source.applyDravenWound();
   if(source.h.kind==CarryWarwick&&packet.spell&&!packet.item)source.heal(dealt*source.h.v[1]/100*source.unit.lastAmp,2);
   if(source.h.kind==CarryYiAP&&packet.spell&&!packet.item)source.heal(dealt*.35,2);
   double executed=0;
   if(dealt>0&&(source.h.kind==CarryElderDragon||source.output.config.primalBear))
    executed=CombatSettlement::execute(target,.12,source.output.config.primalBear?"primal_bear":"elder");
   source.r.damage+=dealt+executed;source.heal(dealt*packet.vamp*(packet.aoe?source.o.aoeVamp:1),1);
   if(retainHits)hits.push_back({frame,packet.source,packet.target,raw,dealt+executed,max(0.,target.unit.hp),target.totalShield()});
  }
  pending.clear();
  ended=frame>=maxFrame;
  for(auto*e:entities){
   e->r.minHP=min(e->r.minHP,e->unit.hp);
   if(!e->r.alive){e->event("death",0);ended=true;}
   e->snapshot();e->f=frame+1;
  }
  if(ended)for(auto*e:entities){e->finished=true;e->finalize();}
  ++frame;
 }
 void run(){while(!ended)tick();}
 // Historical one-entity adapter keeps the prior phase contract byte-for-byte.
 static Result runLegacy(HeroEntity& e){if(e.battle)throw runtime_error("Use BattleSystem::run for attached entities");while(!e.finished)e.advance(e.limit+1);return e.r;}
};
inline void submitDamage(HeroEntity& e,double p,double m,bool spell,bool item,bool aoe,bool needsTarget){e.battle->request(e,p,m,spell,item,aoe,needsTarget);}
inline void HeroEntity::incoming(int enemy){BattleSystem::fixedIncoming(*this,enemy);}
inline Result HeroEntity::run(){return BattleSystem::runLegacy(*this);}
using Sim=HeroEntity; // Existing native/WASM callers remain source-compatible.

inline double HeroEntity::heal(double value,int source){return BattleSystem::heal(*this,value,source);}
inline void HeroEntity::gain(double value,int source,bool bypass){BattleSystem::mana(*this,value,source,bypass);}

inline void submitCast(HeroEntity& e,double spent){e.battle->cast(e,spent);}

inline void submitElderEffect(HeroEntity& e,bool landing){e.battle->elderEffect(e,landing);}

inline void submitCarryEffect(HeroEntity& e,CarryEffectKind kind,double value,int duration){if(!e.battle)throw runtime_error("Expanded target effects require BattleSystem");e.battle->carryEffect(e,kind,value,duration);}
inline bool targetBurning(HeroEntity& e){if(!e.battle)return e.f<e.burnEnd[0];for(auto& b:e.battle->burns)if(b.target==e.battle->opponent(e).entityId&&e.f<=b.end)return true;for(auto& b:e.battle->ignites)if(b.target==e.battle->opponent(e).entityId&&e.f<=b.end)return true;return false;}

// ---- combat/output.inc ----

void outputResult(ostream& out,const Result& r,int precision=10){
 out<<setprecision(precision)<<"{\"frame\":"<<r.frame<<",\"alive\":"<<(r.alive?"true":"false")<<",\"hp\":"<<r.hp<<",\"H\":"<<r.H<<",\"initial_hp\":"<<r.initialHP<<",\"shield\":"<<r.shield<<",\"casts\":"<<r.casts<<",\"attacks\":"<<r.attacks<<",\"spider_attacks\":"<<r.spiderAttacks<<",\"heal\":"<<r.heal<<",\"vamp\":"<<r.vamp<<",\"skill_heal\":"<<r.skillHeal<<",\"spider_heal\":"<<r.spiderHeal<<",\"damage\":"<<r.damage<<",\"shield_granted\":"<<r.granted<<",\"shield_used\":"<<r.used<<",\"shield_lost\":"<<r.lost<<",\"shield_converted\":"<<r.converted<<",\"growth\":"<<r.growth<<",\"raw_input\":"<<r.raw<<",\"avoided_raw\":"<<r.avoided<<",\"cc_avoided_raw\":"<<r.ccAvoided<<",\"deferred\":"<<r.deferred<<",\"debt_paid\":"<<r.debtPaid<<",\"debt_left\":"<<r.debtLeft<<",\"mana\":"<<r.mana<<",\"mana_initial\":"<<r.mpInitial<<",\"mana_gain\":"<<r.mpGain<<",\"mana_spent\":"<<r.mpSpent<<",\"mana_blocked\":"<<r.mpBlocked<<",\"mana_overflow\":"<<r.mpOverflow<<",\"mana_attack\":"<<r.mpAttack<<",\"mana_damage\":"<<r.mpDamage<<",\"mana_regen\":"<<r.mpRegen<<",\"mana_special\":"<<r.mpSpecial<<",\"min_hp\":"<<r.minHP<<"}";
}

Build makeBuild(array<int,3> ids,int glove=0){return makeBuild(vector<int>(ids.begin(),ids.end()),glove);}
bool legal(array<int,3> ids){return legal(vector<int>(ids.begin(),ids.end()));}

Build makeBuild(initializer_list<int> ids,int glove=0){return makeBuild(vector<int>(ids),glove);}
bool legal(initializer_list<int> ids){return legal(vector<int>(ids));}

string itemIdsJson(const vector<int>& ids){ostringstream out;for(size_t i=0;i<ids.size();i++){if(i)out<<char(44);out<<ids[i];}return out.str();}
