# -*- coding: utf-8 -*-
"""Build a complete, auditable item universe from the captured S18 catalog."""
import sys,json,re,itertools,hashlib
from pathlib import Path
P=Path(__file__).resolve().parent
sys.path.insert(0,str(P.parent));import sim30
source=sim30.ROLE_SOURCE
# Normal and corresponding radiant effects share a kind; different values are explicit in C++.
normal=[e for e in source['equips18'] if e['type2']=='common' and e['equipId'] not in (607,608,31002,31003)]
rad=[e for e in source['equips18'] if e['type2']=='guangming' and e['equipId']!=1607]
art=[e for e in source['equips18'] if e['type2']=='aoen' and e['equipId']!=30006]
pot=[e for e in source['equips18'] if e['type2']=='other']
attrs=['HP','ARMOR','MR','AP','AD','AS','CRIT','MANAREGEN','SV','DR','DA','CRITMULT']
items=[];kinds={}
for e in normal+rad+art+pot:
 name=e['name'];base=name.removeprefix('光明版');kind=kinds.setdefault(base,len(kinds));rr=int(name.startswith('光明版'))
 a={k:0. for k in attrs}
 for k,v,pct in re.findall(r'【([A-Z]+)】\+([\d.]+)(%?)',e.get('effectAttr','')):
  a[k]=float(v)/(100 if k in ('AP','AD','AS','CRIT','SV','DR','DA','CRITMULT') else 1)
 # S18 two-source conflicts: keep the previously used DataJ values as baseline,
 # retain alternative coefficients in manifest, never silently blend.
 if e['equipId']==20009:a['AD']=.35
 row=dict(index=len(items),id=e['equipId'],name=name,kind=kind,radiant=rr,category={'common':0,'guangming':1,'aoen':2,'other':3}[e['type2']],unique='唯一' in e['effect'],stats=a,effect=e['effect'],source='DataTFT captured S18 catalog; conflicts noted separately')
 items.append(row)
# Random gloves are evaluated separately: its generated pairs are not selectable equipment triples.
exclusions=[]
for e in source['equips18']:
 if e['equipId'] in {r['id'] for r in items}:continue
 reason=('随机双装备，单独列可能结果范围，不把最好随机结果当可指定出装' if e['equipId'] in (607,1607) else '当前目录明确标注金铲铲已移除' if e['equipId']==30006 else '保留此前无转职、无额外人口、无局外补剂的测试约定；非本轮可自由指定三件战斗装备')
 exclusions.append(dict(id=e['equipId'],name=e['name'],category=e['type2'],reason=reason))
conflicts=[dict(item='恶火小斧',field='on_attack_max_hp',baseline=.04,alternative=.03),dict(item='黎明圣盾',field='armor_heal_ratio',baseline=.15,alternative=.20),dict(item='金币收集者',field='AD',baseline=.35,alternative=.4)]
manifest=dict(items=items,kinds=kinds,exclusions=exclusions,conflicts=conflicts,counts={k:sum(r['category']==v for r in items) for k,v in [('normal',0),('radiant',1),('artifact',2),('consumable',3)]},source_sha256=hashlib.sha256((sim30.P.parent/'sources/datatft-s18.json').read_bytes()).hexdigest())
(P/'catalog.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2))
# Numeric-only generated C++ data. No external JSON library, no execution of source text.
lines=['// Generated by catalog.py; retain catalog.json as provenance.','enum Kind {']
aliases=['DEATHBLADE','GIANTSLAYER','GUNBLADE','SHOJIN','EDGE','BLOOD','STERAK','IE','RED','RAGE','VOIDSTAFF','TITAN','KRAKEN','NASHOR','LASTWHISPER','DEATHCAP','ARCHANGEL','CROWN','IONIC','MORELLO','JG','BLUE','VOW','HELM','VISAGE','JUSTICE','BRAMBLE','GARGOYLE','SUNFIRE','STEADFAST','DCLAW','EVENSHROUD','QSS','WARMOG','FLAIL','VOIDGAUNTLET','DAWN','AXE','DUSK','COVENANT','DAWNCORE','FLICKER','STATIKK','HYDRA','UNBREAKABLE','DEFY','TRINITY','COLLECTOR','ZHONYA','HULL','MOGUL','GAMBLER','ASCENSION','FISHBONES','MITTENS','RFC','SILVERMERE','PROWLER','BLIGHT','WITS','LICH','LIGHTSHIELD','SEEKER','LUDEN','MANAZANE','IDOL','HEALTHPOT','MANAPOT','BOMBPOT']
# Derive names from insertion order, verify instead of trusting this hand-written mapping.
expected=['死亡之刃','巨人杀手','海克斯科技枪刃','朔极之矛','夜之锋刃','饮血剑','斯特拉克的挑战护手','无尽之刃','红霸符','鬼索的狂暴之刃','虚空之杖','泰坦的坚决','海妖之怒','纳什之牙','最后的轻语','灭世者的死亡之帽','大天使之杖','冕卫','离子火花','莫雷洛秘典','珠光护手','蓝霸符','圣盾使的誓约','适应性头盔','振奋盔甲','正义之手','棘刺背心','石像鬼石板甲','日炎斗篷','坚定之心','巨龙之爪','薄暮法袍','水银','狂徒铠甲','强袭者的链枷','虚空护手','黎明圣盾','恶火小斧','黄昏圣盾','永恒契约','黎明核心','纳沃利烁刃','斯塔缇克电刃','巨型九头蛇','顽强不屈','死亡蔑视','三相之力','金币收集者','中娅悖论','碎舰者','大亨之铠','投机者之刃','飞升护符','鱼骨头','连指手套','疾射火炮','密银黎明','暗行者之爪','枯萎珠宝','智慧末刃','巫妖之祸','光盾徽章','探索者的护臂','卢登的激荡','魔蕴','禁忌雕像','生命药水','法力药水','爆炸药水']
assert list(kinds)==expected,(list(kinds),expected)
lines.append(','.join(f'{aliases[v]}={v}' for v in range(len(kinds)))+',NK};')
lines+=['struct Item {int id,kind,rad,cat;bool unique;double hp,a,m,ap,ad,as,crit,regen,sv,dr,da,critmult;};','const std::vector<Item> ITEMS={']
for r in items:lines.append('{'+','.join(map(str,[r['id'],r['kind'],r['radiant'],r['category'],int(r['unique'])]+[r['stats'][k] for k in attrs]))+'},')
lines.append('};')
# profile index maps names to the existing skill contracts, exact star stats are read from snapshots.
lines+=['struct Hero {int id,kind,star,cost,role;double hp,a,m,as,ad,mp,cap;std::array<double,8> v;};','const std::vector<Hero> HEROES={']
profiles=[]
for index,h in enumerate(sim30.PROFILES):
 raw=sim30.HEROES[h['id']];role=sim30.ROLE[h['name']];vals=h['v']+[0]*(8-len(h['v']))
 lines.append('{'+','.join(map(str,[int(h['id']),index//3,h['star'],h['cost'],0 if role.endswith('Tank') else 1 if role.endswith('Fighter') else 2,h['H'],h['A'],h['M'],h['AS'],raw['initAttackDamage'],h['mp'],h['cap']]))+',{'+','.join(map(str,vals))+'}},')
 profiles.append(dict(index=index,**h))
lines.append('};')
# scenario order hero / trait config; all stars, same options and 9-slot feasibility as prior run.
lines+=['struct Scenario {int hero,z,jug,brawl,guard,slots;};','const std::vector<Scenario> SCENARIOS={'];scenarios=[]
for index,h in enumerate(sim30.PROFILES):
 for ts,slots in sim30.trait_options(h):
  if slots>9:continue
  scenarios.append(dict(index=len(scenarios),hero_index=index,hero=h['name'],star=h['star'],cost=h['cost'],traits=ts,slots=slots))
  lines.append('{'+','.join(map(str,[index,ts.get('重装',0),ts.get('主宰',0),ts.get('斗士',0),ts.get('护卫',0),slots]))+'},')
lines.append('};')
(P/'generated.hpp').write_text('\n'.join(lines));(P/'profiles.json').write_text(json.dumps(profiles,ensure_ascii=False,indent=2));(P/'scenarios.json').write_text(json.dumps(scenarios,ensure_ascii=False,indent=2));print(manifest['counts'],len(items),'items;',len(scenarios),'scenarios')
